apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bechlab
  namespace: webapps
spec:
  secretName: bechlab-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - becklab.cloud
