apiVersion: v1
kind: Secret
metadata:
    name: landing-directus-creds
    namespace: webapps
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:90KH0P3gycQyVNBq12rVDOHopChc,iv:rGVz7rJfkk7p+iZYpmc/dfCT+9cj/WFfAeqFvjLuDao=,tag:kp2ZgIXI+PeSvAd5IERG6w==,type:str]
    password: ENC[AES256_GCM,data:t91EEbkiwSG13iNm1JU=,iv:RDeHTBuZMUWofxmKyb8bmRwNoAcc6zmXeOLKCN11XrA=,tag:OxJHvKnsLHwFPC2FHUJwbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZHZGOFpaSW5Udkk3OW5w
            ai8wYXNSMmxTYVpsRFBqQUVqKzBiYnV0REFZClF3dk9UUEx4RHVpaHVnNlpmK3Ux
            SUh5TFNEaHh3c2sxVEVYOVo3R09rMVUKLS0tIG9jdmVkQW5PVG0zV1lVeHhJUUZo
            WUNScHBqMXk5OWw4RUVuTjdxdHhndWcKcKNdqb9VlxOYojWGlWk7j9vZuB0EKlLJ
            AVPhX+nxjENFpf96dIS+gmIOYWnjHXVXy0z8f2pJwCz3iwz7tUgyEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T21:31:31Z"
    mac: ENC[AES256_GCM,data:AkRjbXrG/gpAoTkUqwl31VS0DhQucZ5+kihG8dDvaXOEFUnJNEAaiS/HjcGDUgrQZwFQQFRjVyccjINdSnLsKHT8V35CoqsxFl6JltpRw/EAdmtLVdi9CVLe87oP30cBI88sX+YRwfUXvQzc2M+kyh5ebgj/j3O+X2hsBlZ1iIM=,iv:BmgGUPfsqAHxifEr3gpl/OtezgtgI3YV2ZxKRQmA1Sk=,tag:3lZGOAHeLleNDcKd4X5mNA==,type:str]
    version: 3.13.2
