apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cron-jobs
  namespace: micro
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cron.tools.becklab.cloud`)
      kind: Rule
      services:
        - name: cron-jobs
          port: 80
          sticky: false
