apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: velero
    labels:
        app: minio
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:cpNe4LFt/cb7Mw==,iv:B/5e2oNos1IsMRTeNQntipAFeaHcHPDnKXMCZTiDA7M=,tag:3OScKBzfCmQYBxhQPHWXMg==,type:str]
    secretkey: ENC[AES256_GCM,data:LB+ji5kBlFinqdV8iZGI8QKiLcb9eA==,iv:jFO9+4SftWwNkeJyxc1QI0UA8SEkt+VWfZiNq1cUdX0=,tag:dxXh27w8WbtwvynBNio5ZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eFJpWll4WG9XbmZ5Z1JI
            eGdEOTcrdjJNOVpodnNrdDlxYVdiMFUyakNnCmNEeHhJN2plTzcvLzNUTDV3eTdj
            eDA3MUNaMEFHdmdKdzdLNEFmMkxNUUUKLS0tIGNFQWYyeHhQU3NFTFR0c0JTQXB6
            TnZmc0dqY2Fqc0NaVmRzeHFDRHducm8KcWYiMHjj/JLU+J4UWhnxJzSp9yhSIL+e
            CvuS1G7QiiEA98Tbk6y0UatbEuWo1UhgdVPFhu1M3kyA7B7nMERguQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T20:18:35Z"
    mac: ENC[AES256_GCM,data:cSL2tXLhjr2t4BAaXSSdO/yHw4DKIrfzyjK1y1nsjAJpp7EHdC7DMl1q2NxUnqWFO75ex5IRYwO6/btyUc1t9W7wk2HFtdqbZvF5vHaQONta4Pc6+HuOvlqLpjDOXUg08I/pscigz2mrcqN45G46z8zkeWAlHlwOLFwqZlSbfCc=,iv:dxEAJvt45w+5CCC5BG9YLfomZSMIBZefeZs+EewkwIM=,tag:KvZz653A7Sb0jruLgHeITw==,type:str]
    version: 3.13.2
