apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: velero
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: minio-data
