apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: webapps
spec:
  interval: 1h
  chart:
    spec:
      chart: homepage
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest
    env:
    - name: HOMEPAGE_ALLOWED_HOSTS
      value: home.becklab.cloud
    serviceAccount:
      create: true
      name: homepage
    enableRbac: true
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: identity-sso-media-chain@kubernetescrd
        hosts:
        - host: home.becklab.cloud
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - home.becklab.cloud
          secretName: homepage-tls
  postRenderers:
  - kustomize:
      patches:
      - target:
          version: v1
          kind: ConfigMap
          name: homepage
        patch: "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: homepage\ndata:\n\
          \  settings.yaml: \"title: Becklab\\ntheme: dark\\ncolor: auto\\nheaderStyle:\
          \ clean\\nbackground:\\n\\\n    \\  image: https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=2000&q=80\\\
          n\\\n    \\  blur: true\\n  brightness: 0.5\\n  opacity: 0.4\\nlayout:\\\
          n  Media:\\n    style:\\\n    \\ row\\n    columns: 4\\n  3D Printing:\\\
          n    style: row\\n    columns: 4\\n  Apps:\\n\\\n    \\    style: row\\\
          n    columns: 4\\n  Security:\\n    style: row\\n    columns: 3\\n\\\n \
          \   \\  Monitoring:\\n    style: row\\n    columns: 4\\n  Identity:\\n \
          \   style: row\\n\\\n    \\    columns: 4\\n  Infrastructure:\\n    style:\
          \ row\\n    columns: 4\\n  Gaming:\\n\\\n    \\    style: row\\n    columns:\
          \ 2\\n\"\n  widgets.yaml: \"resources:\\n  cpu: true\\n  memory: true\\\
          n  label: Cluster\\ndatetime:\\n\\\n    \\  text_size: xl\\n  format:\\\
          n    timeStyle: short\\n    dateStyle: short\\nsearch:\\n\\\n    \\  provider:\
          \ duckduckgo\\n  target: _blank\\n\"\n  services.yaml: ''\n  bookmarks.yaml:\
          \ '[]\n\n    '\n  kubernetes.yaml: 'mode: cluster\n\n    ingress: true\n\
          \n    traefik: true\n\n    '\n  docker.yaml: '{}\n\n    '\n"

