apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dashy-certificate.yaml
- dashy-deployment.yaml
- dashy-service.yaml
- dashy-ingressroute.yaml
configMapGenerator:
- name: dashy-conf
  namespace: webapps
  files:
  - config/conf.yml
  options:
    immutable: true
