apiVersion: ENC[AES256_GCM,data:EDY=,iv:nsI5wIf456c7oM8527Hv2cmjF6MQ2q+ArInjRO2GZQ0=,tag:TJOOlFmw03FhhN3Jl1rLkQ==,type:str]
kind: ENC[AES256_GCM,data:1iurggmT,iv:LvF91lHEceujwgjJ5PTS6vlihky0h+Kmw/pnCwGzclA=,tag:0kpojmAw/EclxEKOv6tiJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:u0FBWDK+us5hB4NER9vp4g==,iv:0FldUtDCq1yBE2JiJiCSofCI58h8xUx5VSFcl6F1lBU=,tag:8PBmHsiGjwem/5Y8fEr1Pw==,type:str]
    namespace: ENC[AES256_GCM,data:7R0qgvuOYg==,iv:26jcOXxSwnnCIbtdhqmaSRhcIqO+v721ep5lpDCXH4I=,tag:otEMo0XrdgsrBa2AampKRQ==,type:str]
type: ENC[AES256_GCM,data:gMN/0gnE,iv:52WiSSzJ9HY8RQxipppMdoCuzSHnfjHca9Jsnb6XGBY=,tag:tqBgCkCppmkUqgwrdgOhMg==,type:str]
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:49WCa2e8kUkVly/vYP9GV9gTDuSP2D3Ag71VeItEREg=,iv:Du+FsBY5UmSrj5nXhCkrhiXrMFpv66tFBXY3vf2zo/k=,tag:UsAcCHqGyaxQAXeBEe0Ujg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:o5lPlhIYdCZiu8mPZ3RuofsAVcLYh72BzMXhkgZ2Ipc=,iv:phR9ssIAWJvXP5AqrmnFAHPbFCoW3odWsyCRd7kH4HU=,tag:vLLj5JAUyCCyBpF7xqv41Q==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:7i3hNF1pQWKdfkul7bU37jBMu99jA+KtUbklVSZpysE=,iv:Mj4Q3WpOmFBnLXmZDUFU9LgCLtNuA4sngmJQpGCLQXw=,tag:t0qXgn+2gxRTZpWP8wWLMA==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:ggA2K1nu91epE/M0AxlHyhH6XO4WmE4y+IBeUcQGBUc=,iv:gxJKoblnE50hk6fvtR/c4LppmMIjPfIBUDl88UR3zUw=,tag:HZ6tFeQKmjHV2UXD9mOCDw==,type:str]
    SABNZBD_PASSWORD: ENC[AES256_GCM,data:ipmIjekKBEW2Yw/z,iv:U7DvI0Dfi6WQS/QeK3/HMWXMS5oM1RWXPZqFdaDaabs=,tag:BAVsZ6rDbGMiZYxa0u386Q==,type:str]
    NZBGET_USERNAME: ENC[AES256_GCM,data:XDJ+7yajVgXN8A==,iv:11VDGh4WXGnJosoScY4gux+uqvVy11F/lRMoDLXNtIk=,tag:yhzSdvUiMV8iUqlynlvdxw==,type:str]
    NZBGET_PASSWORD: ENC[AES256_GCM,data:w1lIOT4QULrLN33E8OEm,iv:OYE6QP+Yq3eoWGKlXXcCq9mMgyvRafePu7pbsdA/XHg=,tag:HxYmT6zl0u9IPOvsvHDBqA==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:aNNZhFc=,iv:a55A42t/Y+JeMrJprB+vzee6eKfYAqbIvVRj+vgm0Ro=,tag:IE16Of3XcC5f7ip+Kx7pFQ==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:wKMsPcdeAT5nq/Znvg==,iv:MvsSW15o6kfhNLzr9XJZpzIdsp1t5ii/JjFqnWxMh+c=,tag:c/mYxs1DYZ8ux38rfSXFVg==,type:str]
    TDARR_API_KEY: ENC[AES256_GCM,data:P4q/A1H4Ym1htap+vtNWsgadBZaQsRWw+cUGo+DPm6Bd4xm4FKMpnI3w8uyvbBzYdHjtCwVdORFNhYjVO+DyTtw8Vd/O,iv:2YLRuNLUF2sSJ5+G9Siz/ydAX7iZy4dOOz/8J+09+jk=,tag:1AvNtAYvycx4AHAe7IZrqg==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:zv/0KndytQ==,iv:1+SRF2/NBmV4iwVLj97kpAGVk7gppJSfxQzvPMNbm5s=,tag:x3ByrSvWJT7A4+I3YVlnmA==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:QhuHTaDfr5oJOlAb5P5FKls63EJH4DOUIpODeuy+hUw=,iv:qqAKk1J3G8y8bKExSGNHTzRkP3+E0aLTJK0O15pYvUM=,tag:vJXSDHAen8yLGrBmCKkxIw==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:rJ3ISrAMqk3HT+a+QKJNoeU7tMBgXPIB0mzxFTJ6dps=,iv:jE0SzBXHGA4PSvKI4ZLKiLsI+YvfUKpKxfGksKyBguI=,tag:GzY6/OsOBrJaPc/WKQpgIg==,type:str]
    QBIT_PASSWORD: ENC[AES256_GCM,data:ui05F+s=,iv:BOOcDaWVoe74WUDVc4tkmkdO6qYdEep5VmhdY/VhBQA=,tag:nryvLbDnWNfs5PJauor0xg==,type:str]
    HOMEBOX_API_KEY: ENC[AES256_GCM,data:QrWqOhqFXN33A80svt5eGpoc5QWRJSsOeO41bFYzZbEXYW8u+tduvKVzQVq+SSmuotwmdBzlT3WSa2QFFYWNNQ==,iv:Vw62SlQMkb45gx0IwVtvJ3sm7GvMzSR4xA9yS4rAJmk=,tag:AMrDRJRzSGFSvLXbXMBTAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWGtQOGthdU56US9yYVpV
            Wm1TYnJ3TENGWGhUeXp4TFl6Ti9iYzBhdzBzClpHd3RwQ1RCZ2hkaW5FU2NSdkV3
            RnZzREt3VkhvUUM5ckN3YTNrR2o2bW8KLS0tIElJT0phRTRoOEN6QnZVNXlObkdx
            WEJ4Qi9MbnF3NFpGWlB1WTBreXIyaVkKiSQyTncwASO7wEYtrevF2SenYdoYiMrp
            SvqVrgyhAEHSI8FpEb5jjYh+LIhLiQjK0mT0w89Lxk6X2oUEipfQaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    lastmodified: "2026-08-22T19:54:56Z"
    mac: ENC[AES256_GCM,data:+OS34jEMg94bT9swvigX+8SzaGci3Gu6y6XkCm0uR3ZjO5Zb6HxSSql2VFhhnncR8A6ROyMfliRycIfCf7Zaw9sL7YELBm7sUmibzPmPItYNETWSYD2HNJZfXqwtrqGtKDoFulh6TwfTIUyfuw9gUPCZEniBv4jr8Y8MF/p3cGA=,iv:IYz7v81FlMYPHQBYRqengzmb4lxslwPZ21wI9bs744E=,tag:uUuNV5j3I0N/Heq7XQtLIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
