apiVersion: v1
kind: Secret
metadata:
    name: homepage-widgets
    namespace: webapps
type: Opaque
stringData:
    #ENC[AES256_GCM,data:nJUw/FLoD32rM04=,iv:R5TO4l4CtEoarpFXIiC/RK2tWMExJFT9ZLIRwFzjxLk=,tag:D8yYznbdBrZw0l38Idsubw==,type:comment]
    SONARR_API_KEY: ENC[AES256_GCM,data:reZG/MqYCTCjMX3tn3tVMbCYyyAZbNGhXb3I4CBL5g0=,iv:srsj9W6PdDwvEiroTNbEfO+XbCdh2yeVny8+NsEing0=,tag:JYPXcE0bkXdb8G6ULWwKzQ==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:AFpTBLzsOLdOR0ssUG3m27sL0pFuz5CxACj2pn7OmHQ=,iv:mIIPBrZ+0as4rSD5KObFJ6nx/rwNYIu1h340uyVX2f0=,tag:lLhJhDo4tz+mihAHN4r2yA==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:R7lnMOah6Xu0vdfSuijyfkLyxqpWakmOrkk+STn0GGw=,iv:Sg7qMQLv8p+fpDfzxk+75Cqc8eqX04Fd/+hPlJ3LUFs=,tag:mGLbaXir+IUNsVdXAX0qCQ==,type:str]
    #ENC[AES256_GCM,data:wJqCToEasUQ=,iv:U5MkZFvdF7W3ODzhDMrS2Gbp6hWJUKbll+Jult6JAIw=,tag:PWqLKAOWvbQlVSiWWa2uHw==,type:comment]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:dCTCo4VuQYXWXaBsDLh4MLE7gdZUatB7UUQJS5VKhxw=,iv:yaj7MNAbYAVeLMLp62qNVtesttbB3UloYW1yjrMgyvQ=,tag:1Vy8qqKK/DcR5nC8p7zBCg==,type:str]
    SABNZBD_PASSWORD: ENC[AES256_GCM,data:RpG+QlrDYrQrmRL/,iv:S53WMBg+TZl9MwtOQm/vMQT+y299lIkIc5ZulaB39PI=,tag:45nWjpZiqH+pnadDdfQd0g==,type:str]
    #ENC[AES256_GCM,data:yr9lMeoubA==,iv:xVtB7/QDzIhMyGJpLTqO/OhY9zbYrvwfSDM7Bz3Oc1Y=,tag:VkhTcbV4X0gH1q3aBH+x8A==,type:comment]
    NZBGET_USERNAME: ENC[AES256_GCM,data:M5x6Ug8D0SvmZg==,iv:O2P5GkoLBHpPTME4S1cdBC104LdtxnmzOKBI+I6/zDU=,tag:md0JDr0KMCwhO/Dr9maozg==,type:str]
    NZBGET_PASSWORD: ENC[AES256_GCM,data:XoTiVtJq72ef9Xbr8Lax,iv:TIv1CCYfQaGAUvulRTaiPyZDnH5iA0+ewbjsr4X4O7A=,tag:thmhnFT9pNL4QXsUm15EGg==,type:str]
    #ENC[AES256_GCM,data:U7oW/IKBGu0=,iv:prdt8+Om3gnmgObBfDVWtarNpbRP1DnLncO55CIaL80=,tag:+YXf+/2khuJQjDlP7lb7ag==,type:comment]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:0v3K43o=,iv:NhAqhe94G5hbIHmXXbX3QiD8BCqj9AtNtKE/YPMPA8o=,tag:QgBUvQo5osrqepzYUO+OvQ==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:sSw8bGrPIuZPLzht7w==,iv:9D5Vxdj2uX1OWgeE+DeoigLiqIxInOscQwulagPXVdc=,tag:YfqdAmls0RebY1cmZZ+ILA==,type:str]
    #ENC[AES256_GCM,data:dqJlc+2WJxOoX6VCxmAuCNk+wqAtHUgj92KxbtUF+YJVZGpPMg==,iv:Uq2h6S7Fk+VQQi7CWvRtW87fAF0rPwDoOa/z9OoqPkI=,tag:E2DABCXrXKNnG00gTgUHSA==,type:comment]
    TDARR_API_KEY: ENC[AES256_GCM,data:yLsEsqKQPNxD8pB2e1jfwiyjZs/fH85tfoza9E98/f2doPTGBrQLUFFMYP3tfQNfPJPB5EOC+YcFdMCDiySZw+bb5sqE,iv:ubUNnXZ35ru1mkZKm7NbyxcW7ufJf2V7bbxLHghQpvQ=,tag:dOqxEea9soWyCj7M5D5Jcg==,type:str]
    #ENC[AES256_GCM,data:z+01XO34OOm4z9QELUh3,iv:HHXz9USz10YKTxaP1AZSJA9nzQZBjoyEWz6OAv2bpE8=,tag:KhcRxvj0m+AYhgtryZh/fQ==,type:comment]
    HA_TOKEN: ENC[AES256_GCM,data:K4/1MG2dpA==,iv:VcXptSg70o8AQXTY33WbxpwJQWzMC9xDxEZZXUCB2bs=,tag:zui5T373RKecnQuV5aTYyQ==,type:str]
    #ENC[AES256_GCM,data:I5KfErzKl4W6c+4FAYCw55uL/+8IhQD+Ft6Nr5YeWolIqxKr5vNkeKhoWQ==,iv:+RyY4e9uEhUROGkeXTZ0D75tt4RBnR9lGIvy2tHMG14=,tag:AdjWzj/k16tyKM5r8xwhsw==,type:comment]
    #ENC[AES256_GCM,data:TXqXv54inwkCkwha4jSnif31b3zf8sqEfSqMsIFyI/4ZjJSgm0aPWikz,iv:2CPZg6CHmuh0RQCqR3f3Wrju0QVGzr8vdNr4Ao8ydME=,tag:CjDB4P+juGmTt4I7V4xWIA==,type:comment]
    #ENC[AES256_GCM,data:KYVc6+P9XZnp/SRm+Dmm7rflNMDPtX5pYqhIHm8pwaPpG35ov783Dw==,iv:0XaJ/6IvWz7PYMRQsEo1+vFr4mxaoa7Z7ayPNw2X2UA=,tag:2Ol6rTd4DlpaFg58I+llxg==,type:comment]
    #ENC[AES256_GCM,data:ZPVCXNDiAJ1d4vnVXF0F7MpaxszBxVQI8upxtjr7aEvy0g==,iv:i6PEMSBqeLjeo+W5Fd0ArO2Ba9MWfUzcagjhsp3IA04=,tag:KCo4xlcCjg/aB4D0QNKuuQ==,type:comment]
    #ENC[AES256_GCM,data:tlBphTvM0x6NN6GPXrxtlwyoLIVu+yrrdpquvhnIHQGyvw7VCDgoQ96ir/w=,iv:lH76usvorQwl3dm1I58LHmfB5S3wdUWwNzbqr656Km0=,tag:WqQyF//LCvl8bYKicWJ4ZA==,type:comment]
    #ENC[AES256_GCM,data:KFIOPS5wQPYCR9sGu7obb9LX6jLhDQ0+2D9ZdwlwmX+joZWRqxCI,iv:nlHMwv/CfPyWPDOuWlPQZ5dYvWJN7LvXAwUdJW9rzHg=,tag:bW8zHd1aIAO3/asGjcmEug==,type:comment]
    #ENC[AES256_GCM,data:hKpDpJUNx7rGPardtYCl3qgSJ7D3LxnOfrdorL2Jt073lxZZ7aHMWA==,iv:Tk2F57MhkngxBzP+CywR8CUlkLCz+hPxizC9emAPws4=,tag:gN9kR0UwDAMX8iJZ6OEwCg==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NWw5cit5QmlJUm9PR01M
            QW1DOVRGYmRjUkdpS2xUUkdwcjg3Wmhaem1ZCmViUUxnNVNReGFhR1VlTDgxeSs0
            dFR4U2UxTGVWOTVaTTB3Q01YdkllMEUKLS0tIGc2Wit0bTUraSszM0NWZENZWFF0
            REpFNUdIMElVVkRrOFpVa1c1ZmxuZ00KiEHNDrsB1VrVHnneuv3lN4yiwVNBHFfU
            P0F1TOlnNvCemn799KYH5MDkSGTc7QDQFFYoUsqHrD+7xYIbY+ww4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T23:26:30Z"
    mac: ENC[AES256_GCM,data:Pas8sJiqFydoMUuHITFxmQLBzzzhD00BtpYDRW2noOMqxOlP2wzu687x49hwa4R2KnPu4/YQFsRwS14zMlUSGpDaHut4RIaORERMMp/LSMk2vNRJFP8RvnRLoz/akmXWew07ZkJy2s7NP7fXji0DxiZxLTDSMYNZHA2c5NXLJKY=,iv:kV16VlucyDg+8ZzeT+MWP+OsGdZklBpVO7kD8HShu7Q=,tag:HW7eZ5lbI2CBp9CTJtijdQ==,type:str]
    version: 3.13.2
