apiVersion: v1
kind: Secret
metadata:
    name: lldap-admin-password
    namespace: identity
stringData:
    admin-password: ENC[AES256_GCM,data:cQtAyCS+UM+e/rzsAJ95wywUoPi8KlSJ,iv:w1nw7aFFuUF/4RW8TX4ncxi4KaDKx3695JFFm6+feDg=,tag:/S1yxzZ+nqQV40dVlTIK1g==,type:str]
    jwt-secret: ENC[AES256_GCM,data:fXQsBuRFUlbHYWwB9sTSmQuGb+Tcf5mJUR4TVYIeNPhuFEDXiJ5PKMexHzyOIPOUiRQqHfhHwmjJ8ibhvR/7VA==,iv:6wjUhxyhd7ZubSLUUFqyQDN3fjzuqZatWfNTuAntTDw=,tag:5EndeCDvGur60YiOsGZhIQ==,type:str]
    key-seed: ENC[AES256_GCM,data:SaIFqB/s1Y8jDs6TdEDeZMbsCEv0rRbpISg7zq+WtW2LiSb00nG83cuoBupGo1K9NNqByvQMCShGFfUBqJl2cw==,iv:z4PkPppmjtmHfs9lkz93TkBEwnfZItukfSeDIT5y140=,tag:GRx0DhB5oK4GZ0GnSPhb3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQTBWeUg0YzJvUWJqcjVh
            MXJmMXpQMXZIWDhTY2ljU1E4aDB1bXdaMERZCkpFclM5OG5DbFdHck5yRWVrNitJ
            YkJiamFFT2E1T3ROakloZ3E3TnhaZkEKLS0tIGdKcUN4cmp5bW42Y25pVmFjdm4v
            WURZV3R6SkhVN0tTa2NKczc1ZytmRVUKAUeDh6hH9T0cHRMNrPNlDEuQi1HZ3U1S
            6y+WxN5aZyQIbO7HpIwluyd9uzXHROS6xgbqmn97qyq7bh+7mcfttQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:32:17Z"
    mac: ENC[AES256_GCM,data:DzNKVPywRTHxdr3iYABDaFwZetLwPIIeh4Tb/tLoVL+rGpUzeh3ktCshSN3RTNcEB+2bew4CtJWglCHtvc9wLM6uaPRo9kIQWrtDeVdo84CvIhGusyG4K5tC3asVr1NfRTy83JZwWjefui7Ov88tl8YV5leoeDtFHUZxTIasm8s=,iv:QciwD7In6WnyfTJc43EftNvYbdNgDlYF6gypzJb6lMk=,tag:NnbKk02bPmkdebIAdtQJTw==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-database
    namespace: identity
stringData:
    password: ENC[AES256_GCM,data:r1cBTQjEzJmihDPZCIaB1eU+ng2F9L63tvCBYazvC0PxA+QMbP6dz1pt424cR2QkMCN2jOkD+MBV09EtD+kGCw==,iv:tUCvLxAL7gm/O+/u7ROgPSJB8HBP4MCVUUQHAGYKUlc=,tag:5aLC27UpcbB7WlS5Jx6Bdg==,type:str]
    username: ENC[AES256_GCM,data:IIVg5+4=,iv:okJ77QlKSRLH7HKV5PjldRd0bAcAaeG49i0jN7vsX/s=,tag:eDE71FrVf77ZRv1KFr1kgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQTBWeUg0YzJvUWJqcjVh
            MXJmMXpQMXZIWDhTY2ljU1E4aDB1bXdaMERZCkpFclM5OG5DbFdHck5yRWVrNitJ
            YkJiamFFT2E1T3ROakloZ3E3TnhaZkEKLS0tIGdKcUN4cmp5bW42Y25pVmFjdm4v
            WURZV3R6SkhVN0tTa2NKczc1ZytmRVUKAUeDh6hH9T0cHRMNrPNlDEuQi1HZ3U1S
            6y+WxN5aZyQIbO7HpIwluyd9uzXHROS6xgbqmn97qyq7bh+7mcfttQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:32:17Z"
    mac: ENC[AES256_GCM,data:DzNKVPywRTHxdr3iYABDaFwZetLwPIIeh4Tb/tLoVL+rGpUzeh3ktCshSN3RTNcEB+2bew4CtJWglCHtvc9wLM6uaPRo9kIQWrtDeVdo84CvIhGusyG4K5tC3asVr1NfRTy83JZwWjefui7Ov88tl8YV5leoeDtFHUZxTIasm8s=,iv:QciwD7In6WnyfTJc43EftNvYbdNgDlYF6gypzJb6lMk=,tag:NnbKk02bPmkdebIAdtQJTw==,type:str]
    version: 3.13.2
