apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: affine-tls
  namespace: webapps
spec:
  secretName: affine-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - affine.becklab.cloud
