apiVersion: v1
kind: Secret
metadata:
    name: affine-db
    namespace: webapps
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:AhdwWZfE,iv:lXSaQRi0MB+zyDwH5V4V9YxsxleEV7XiWJ6I7ESWEls=,tag:KdPY69khTGxTbU0RJnZZWQ==,type:str]
    password: ENC[AES256_GCM,data:fZRyMNdTTQMcROkgbkWh63ELS7ULQdIGq3AJfO2s69F38VTW11dDxA==,iv:kvLWKVCGlmt+j/vyOuRVf3LeCauGcOf/RbhW3lRQWqE=,tag:ZSDBL5rpEhgZOuF//pQc3w==,type:str]
    database-name: ENC[AES256_GCM,data:RQDWxPTO,iv:GhWT3Wjc7EdScffg2rbOwLO14Q03q4Q0A44urS03+8o=,tag:WQzthSlRW4jvQhSEQH33rw==,type:str]
    database-url: ENC[AES256_GCM,data:ARTEkw0OQJL6wIdD0fejjtBtZ7e3HruznHkv+hph1kb4r/Gw91OLZJHIDsiG0+QqQaQ3/F5jF4COljPDNedXuRvNmeVqaiir/qF080yZVWqWPmGtd2CnKjRST6qZSGLVRMf+o3u1Nx0AJbldOvNcUJEM,iv:xg+cG7+pT+gm1QZqUreA0NIcdQEScb0CkSHscmpy1hU=,tag:TBfYzA9iNn/wpDNtJ6twqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZEdhd0FRUnhDYmVMcjhL
            UlViNjEvcStKTkJjTmh6OW4xMDlkcmRNcW1JCm85Z3JBcE9sNkErckJEYUJPSCtW
            Q3B3Wk9DMGs4aW5JZnNGNExCYitINWMKLS0tIC9oM1granMwbkdrRlVsNnluN1RU
            ZlJrQURIZTZjRy9JSGNIN3B1WjlBQzgKtLP7948784ht6+Sdc6hZrAysclh2sqlW
            dZR2e+dUHENvv2Rmd+jC+9ARLsSVVwXQGkaTAol4WnjNEAVszRIXqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T03:03:48Z"
    mac: ENC[AES256_GCM,data:UoD3UNKp9jCo/8RAR+eHPlhRvm7CdrMnM5f3lQ7ZHkRL9px8g+e2yRuqNGe034G0hVQA9q9O1gKVFBmz4moee6xKhn9bR6gjOlfcyg6dudonc12RfwOj7cpzNROg8la/iM1nIzjoZRpzwZY8roCUIsUDbt+wHldBJbkk40mfG+Q=,iv:quKfHi1rTUYpRjq/OBpiZjqhTvyR3nkpLq+RetwHFHk=,tag:852IPJDspqo68h14c2O3FQ==,type:str]
    version: 3.13.2
