apiVersion: v1
kind: Secret
metadata:
    name: affine-db
    namespace: affine
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:UNu62lLZ,iv:paqgUwt1fcxcsSD2ajAmh2ao18zpYcqZxCuIMQ/5KUM=,tag:lKkDzXk8EvVwBdtKp3Eynw==,type:str]
    password: ENC[AES256_GCM,data:N8F9joUQqMc2xifTR+2D4/eFjPlhGQqIxIhvooPZ7lYuZ18Z9P+uXg==,iv:R9ChPlcy3aBQjlpHbYjJtK2eGMLJGhzlS6Vkm9q06RQ=,tag:qJFXyfN/6opdiIgEURHgRQ==,type:str]
    database-name: ENC[AES256_GCM,data:bYMplRKS,iv:Ed2zGbNzt5HMzhxbbt7wpfXZ1E4bN8jf47tHzKWmh54=,tag:cmAcUPPra4pYx8MQVnkfeA==,type:str]
    database-url: ENC[AES256_GCM,data:AbbwM8QWok+Ve9t8fThjNgUtqf5roQpvfDlbdCehVVGFV2uSPyNCCre3eBO+xQTnLe2ZEsWfIA1KzTg0437R59jVYer4jh3/nmfmuCRu6wH7UGurHuvjJVjulDqnH2DEM+0jHc/KzLBpLaDroawIJM0=,iv:3oYv8Ck0VHtabmqs0RiWlm4bxYtqELYRR7BKE7OwEHk=,tag:dYbMXz8PJiuUM0cQ4s3NsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzelZSa3FoMUhkbGU4MWM5
            R25DY1ZTUGx3Z0lzU044NTd5Tkowckd1WDNnCnZVWThOTURPcjlkVFdFa1N1dmtm
            WXMzakFtaGpVNzdldFBnTnR2cWU5VXcKLS0tIE54cEpGaCsvQVZVcmVTWFlWQU8w
            MFRnaUVaQVl3RURCdm5TR3FKcFZWOW8KKxVHXc43qsc2pxdeCMptPuSDkFEQDDPc
            BuvcYjJAVa+L5a9RfJ51FZGFPiou1dK0PyhaU+cB1gwQ5thwPtumyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T02:04:25Z"
    mac: ENC[AES256_GCM,data:38kCy28wRBvw4mp6eK/vrXxncR8pyBCG3pQMUYcyAqc+IbNqY4BSerVx2t4FpJlURFxqIzY9dePRaPgWZ62OXcQ+0Qk/wiuPmdU8OpMFHObS3KXpX9gQ7DdRPPVveGvc9ZCKsyU7xNJVNDXpg3bhFEpr6F5gMnPUPks7L6naBXA=,iv:1owxxRu2Wt40h6FM4mTCchECx3gLN20KMk2wbq//zUE=,tag:urJoQs7BS3Y/pbFBVpRe+Q==,type:str]
    version: 3.13.2
