apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-password
    namespace: identity
stringData:
    admin-password: ENC[AES256_GCM,data:oI0i5IqCL1C0CA/wCzc6OiPgyu6M7w8H,iv:lGBPBH9rWmXptzIwuayReGmBXZ3s/0HQqvaOvoDd5w0=,tag:3WRMAkWbcaKIV5/ATsGVqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY3BsWjBJN1J2alArN1NC
            L3l4NmRhVVVqTGJCdFVud09kRDErK0lPUTFRCko0N0lUUWFDUE1Tejl5SHpwaFdV
            dEtaQW1sTndqSXE4dmI4ME45RlJZbW8KLS0tIE9iVjR5QThiQWdtUFFzdkhYN3Vm
            UFdlbG40R1JJbFQvQUExT3o4OSt5ZlkKSLQz5yRSO/LgtU3aiHuWVV8PKoRHRl/G
            7Uoa2KDopdY8iocRWY7jsxAHJIrKvawZUfCWUdScRWlbjK9ujhYZ4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:33:13Z"
    mac: ENC[AES256_GCM,data:xbOrDF9DjH/RkaKnf3ZJ6FlB0ufGS3oEBI0Fll8+//xTXrKpPJ/MY1hS+ehkmZgTv/PnZUfdgqi3ZMmgo0xE1VAY07xTDcNSdO5jMDz9RUBc8+J2Gxu7mSyqGIAtSyhz6dxIf+18pQvlCvIyJMClTFS4dZ86LP2CmkuRdJJReCk=,iv:RY6ptcEY87BKM8htGeTF7EXHf7us4ThUXnLt0mIKD8w=,tag:tnQKBgH7onQagffSqqSVRA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres-password
    namespace: identity
stringData:
    password: ENC[AES256_GCM,data:SjsZpu0VJc4Ly1IHLmbt2G6qc/kNs6Xu6Py/NJWhhatffDEY3DOG5BbqcETs7GHGizhjFFwmKcjKGtn0r/VWYQ==,iv:qisD4g6/CQiHjIcmyQPee5jDtG0QhrPPYrQdWWJiuZU=,tag:4MHbTxy046oUiw/NlbqD1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY3BsWjBJN1J2alArN1NC
            L3l4NmRhVVVqTGJCdFVud09kRDErK0lPUTFRCko0N0lUUWFDUE1Tejl5SHpwaFdV
            dEtaQW1sTndqSXE4dmI4ME45RlJZbW8KLS0tIE9iVjR5QThiQWdtUFFzdkhYN3Vm
            UFdlbG40R1JJbFQvQUExT3o4OSt5ZlkKSLQz5yRSO/LgtU3aiHuWVV8PKoRHRl/G
            7Uoa2KDopdY8iocRWY7jsxAHJIrKvawZUfCWUdScRWlbjK9ujhYZ4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:33:13Z"
    mac: ENC[AES256_GCM,data:xbOrDF9DjH/RkaKnf3ZJ6FlB0ufGS3oEBI0Fll8+//xTXrKpPJ/MY1hS+ehkmZgTv/PnZUfdgqi3ZMmgo0xE1VAY07xTDcNSdO5jMDz9RUBc8+J2Gxu7mSyqGIAtSyhz6dxIf+18pQvlCvIyJMClTFS4dZ86LP2CmkuRdJJReCk=,iv:RY6ptcEY87BKM8htGeTF7EXHf7us4ThUXnLt0mIKD8w=,tag:tnQKBgH7onQagffSqqSVRA==,type:str]
    version: 3.13.2
