apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-password
    namespace: identity
stringData:
    admin-password: ENC[AES256_GCM,data:37VKbR8AR1ZvcQ==,iv:pvg+st5hWlwifC8G7/oXtzQdyzmYxEAF7++l3l+3LI0=,tag:LxY3+8TjHer+rvhuPlTaEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S2dCZzlEdU9xZi8wMXNk
            bVpsK3cwbnpkcTBEQVhGeWxaNGJ2NnBvV0hFCmpENTBKSHRDU3VRVFVyNWV2VFBR
            TkIzRDNUeUlRRkZVOVM1WHJ0WjhDeGcKLS0tIGJHOUpOcHNIMjlHR0hIM2JaTlU4
            aWRxSDhLTkdyU2pxMHF6T0NGUVVEYzgKXZjREQQl9xXwA1HjqhvUQJMgasJg2B40
            fKVPPVbVLfncP8qFersi4mzrTvMKsIFlFvsR1YFB0sLhLrpnGseuFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T18:31:27Z"
    mac: ENC[AES256_GCM,data:NacNa4yqR/YFLZGVWUAOvGEPKqQ+1kw2jko4SY1rOVjHQ/ctk+qJjxQmrn27r0ec6uNIFhB8rieUjo0539qWsfJXyghnEbnPWI1Zfr3tsRrSRHvDCO1M/WXLjWH41+zflVFc6uMC3HwIsS9xpGAJ5ZpmWSkVFRbX8VgqnnzjIR0=,iv:pGYFh020f2KchCIOl8O4rBPaT8lJ2+fQvfLxmWd0nrc=,tag:5emH1nn/Xo1Mu0wSwDzpOA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres-password
    namespace: identity
stringData:
    password: ENC[AES256_GCM,data:5uaL6QfB06Z1ZDTNWB8IBocNBnnjcBY++DEb7mj3oYU2sYicZI2ZgTg2ZNzTO9ILf4jeTFYvM4FkBwhzdSmjpg==,iv:nN1fTsCG+WB6apTA+NAfjqysnsSp8F20SQoFP5vCqSY=,tag:DC7hADvG4zJG9lnzxSUfuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S2dCZzlEdU9xZi8wMXNk
            bVpsK3cwbnpkcTBEQVhGeWxaNGJ2NnBvV0hFCmpENTBKSHRDU3VRVFVyNWV2VFBR
            TkIzRDNUeUlRRkZVOVM1WHJ0WjhDeGcKLS0tIGJHOUpOcHNIMjlHR0hIM2JaTlU4
            aWRxSDhLTkdyU2pxMHF6T0NGUVVEYzgKXZjREQQl9xXwA1HjqhvUQJMgasJg2B40
            fKVPPVbVLfncP8qFersi4mzrTvMKsIFlFvsR1YFB0sLhLrpnGseuFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T18:31:27Z"
    mac: ENC[AES256_GCM,data:NacNa4yqR/YFLZGVWUAOvGEPKqQ+1kw2jko4SY1rOVjHQ/ctk+qJjxQmrn27r0ec6uNIFhB8rieUjo0539qWsfJXyghnEbnPWI1Zfr3tsRrSRHvDCO1M/WXLjWH41+zflVFc6uMC3HwIsS9xpGAJ5ZpmWSkVFRbX8VgqnnzjIR0=,iv:pGYFh020f2KchCIOl8O4rBPaT8lJ2+fQvfLxmWd0nrc=,tag:5emH1nn/Xo1Mu0wSwDzpOA==,type:str]
    version: 3.13.2
