apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homebox
  namespace: media
spec:
  secretName: homebox-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - homebox.becklab.cloud
