apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tools-becklab-cloud-wildcard
  namespace: micro
spec:
  secretName: tools-becklab-cloud-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.tools.becklab.cloud"
    - tools.becklab.cloud
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
