# GitHub Container Registry credentials for pulling images
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: micro
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoieWFwcGluZ2JveSIsInBhc3N3b3JkIjoiZ2hwXzQ5a1huNVZpQ09kdWh6Z2V4Z1BWVE5XRHFLN3VHOTJaTHFhdCIsImVtYWlsIjoieWFwcGluZ2JveUB1c2Vycy5ub3JlcGx5LmdpdGh1Yi5jb20iLCJhdXRoIjoiZVdGd2NHbHVaMkp2ZVRwbmFIQmZORGxyV0c0MVZtbERUMlIxYUhwblpYaG5VRlpVVGxkRWNVczNkVWM1TWxwTWNXRjAifX19
