apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: micro
resources:
  - namespace.yaml
  - middlewares.yaml
  - middlewares-tiered.yaml
  - build-jobs.yaml
  - certificates.yaml
  - ephemeral-storage-test.yaml
  - services/
