apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hasher-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 10
    burst: 10
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: shortener-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 5
    burst: 5
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: converter-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 20
    burst: 20
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cron-jobs-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 2
    burst: 2
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: dns-monitor-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 10
    burst: 10
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: webhook-relay-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 20
    burst: 20
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: yaml-json-tool-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 20
    burst: 20
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: qr-generator-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 10
    burst: 10
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: image-editor-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 5
    burst: 5
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: beckflow-ratelimit
  namespace: micro
spec:
  rateLimit:
    average: 10
    burst: 10
