apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: affine
resources:
  - namespace.yaml
  - secret-db.yaml
  - pvc.yaml
  - postgres-deployment.yaml
  - deployment.yaml
  - services.yaml
  - ingress.yaml
  - certificate.yaml
