apiVersion: v1
kind: Secret
metadata:
    name: affine-db
    namespace: affine
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:gm/pqY29,iv:f1iH5Iya/atvobCGN8EidIE8ZKy2AlRhsmOnUWbYUOo=,tag:nyDmfEbE00xyaEGNGbfklA==,type:str]
    password: ENC[AES256_GCM,data:104pX2UI2A9QfQ5IdJ646YQVPuNOuuJNouAFvFd2E+rYoSsJh554Htsv2XA=,iv:u/X9u5RmFrBj10zuxH9pYRTGeFH0oP5wKT0y4ZA7O4k=,tag:TYTO9rMOn3O6ou02KApd/w==,type:str]
    database-name: ENC[AES256_GCM,data:ptkoq+HX,iv:Om9iTI7/nqVLwG2meQq3TSvwti8MkA1zMxphv8dshdg=,tag:TzRhXfDPaXDYmEx29w2kGQ==,type:str]
    database-url: ENC[AES256_GCM,data:DyZzEIWNHLxpeVywllXGf2zVTx3JK5WVuQMRPy0oEE8LhWZZOLsdVOcW82IqC9xyy4m6b8aO2IC3ciVo5OkGJ0Efzr26fBUqdjcYMTOqfIILyAYRgbjCG0FlRLsk+eGO9yTbSGrjDeLJhrfJB5DEERfUHQ94,iv:/9VDM2QITL3wDSTGJRObiBPlM1APtIOUqrpl2nrwNFw=,tag:UjsnR88vMs67rUF/ZUf76g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcVF3YThzVFdJOTR4WkpV
            TzBESllacm03ME1iaDFQK2h6V2RZVFArbXhBCk5kYWpMMkZBWUFOT3lJcjE2MmI0
            V3daZzdmbENYM0RSUzNBdW1JbFZWRGcKLS0tIE1NSmJmLzlUYWJiNkpFWE5MTGFh
            dHdGMEV2YmhJSDFUZ2JhbEpDek5nVkEK113z1tNAREbXVW06y1oZ2do7QQ8LDGH+
            rzAEJM2Wf5RfdBAwZh053mEgfACZlX2mmcyigc15Cbg0xQ7Lzigpjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T01:50:38Z"
    mac: ENC[AES256_GCM,data:5fI70tvYugVCtUpHG0iqVrU29dQQw2KT/pKyR4yhjWoe6+zWl+8w4eLWxewblWGHK7bceAQMZYPATLr7ywZU27PZVd9w65MnQ9vQsVx+RKFGw168wEGIQLoGOfsXBCAnoZDWrQnS55zES2WiC+/NGETVc6ryXTS0dtyog8KvuM0=,iv:5Hh+n4j0gGIrw5+fAzHAE24zXlfG5Y/N0FgK6jmOrfk=,tag:uvbNjuKFpGDL+zhORBUSIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
