# Auto-split from cluster files
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openclaw
  namespace: webapps
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`nova.becklab.cloud`)
    kind: Rule
    middlewares:
    - name: sso-admin-chain
      namespace: identity
    services:
    - name: openclaw-gateway
      port: 18789
  tls:
    secretName: nova-tls
