apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-data
  namespace: webapps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
