apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: toolbox
  namespace: flux-system
spec:
  interval: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./flux/apps/toolbox
  prune: false
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: beck-cloud-config
