apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nzbget
  namespace: media
spec:
  secretName: nzbget-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - nzbget.becklab.cloud
