apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spotweb
  namespace: media
spec:
  secretName: spotweb-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - spotweb.becklab.cloud
