apiVersion: v1
kind: Secret
metadata:
    name: spotweb-secrets
    namespace: media
stringData:
    db_password: ENC[AES256_GCM,data:MT5wJOTUeF1Lup6Rt9sEKZjCQMuuoZ2G4OMHpOGPpRj+k54=,iv:N8eZVKDZdpOysJtYnU2ETTwvLIecktDWPj464jY7bpQ=,tag:iWin0W5/vAcoonNiCsihcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK0Mrc3RGNmQxWnJDL09V
            dU5mc2ZPU3dNVS91NU53SngwRWNuMkdENENNClB4SHJQa3U2R3E5cUd2SnlyRHlr
            d1NuRVEvdGoyeSszUG5ZcTZJcFhZajAKLS0tIGxBU2g2T1UzbzFRbThna0xFVzJ6
            MlVWR281NittbStlOFhPdjhOQjJhK1kKfgmSQ2GKB+tT1vSYHNFLNGF6afSJU7fc
            XZNS0UhNdMGy5tYv2HDYquvxYMAgUnOeTXjYufoy7EvoGCekPDIIgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T15:05:58Z"
    mac: ENC[AES256_GCM,data:KprV3JK2FLEDJ6x/aWPphKF0puSGGOv/VaID91DaNlHWKxpW6Bz346pHESLzWvanb28JPwtZCzlfMdOKfj88btDzt0s7TVcmosfjJDzc7arAj2hS1Txnoj5qzXRI9RuZW7U4CO+h+FxVCWSJc0EvjVtxGng6bkgtsHVb9LlTYtI=,iv:Somf9z2x/RM4kBJl1gfVwo0UJi9+ADWJdcHZ6hfBNZ8=,tag:wmanhjPCJ8tQcciqWRRPHQ==,type:str]
    version: 3.13.1
