apiVersion: v1
kind: Secret
metadata:
    name: cadam-build-env
    namespace: cadam
type: Opaque
stringData:
    SUPERBASE_ANON_KEY: ENC[AES256_GCM,data:+Yi1WOhv54jR/AYMWWIPZYYmbqHZhOyJLe7uwowlyPrcRqHhYPRR4Jqgg9din/jcP+NtZUl+9f8SANh8ESHJi0fal2k7htAVwtzZqFEtBHUP8PVfoge7vkK4/W2Y6z2nYBvtz1t0dsoAGJvnxus/ke4+1Adlpa1tvuqFBOmXQlSFlAaEhBGii1Av/nAR50g40s33NjS4xWMD2cUzzD9aerfhBGjpaerR/g==,iv:WoZxEQVXzsLjz7iaoRX8qzdn9KYZWaxaODre+eZLbl0=,tag:DS9QlotNww/nD/P4e+XH/w==,type:str]
    SUPABASE_SERVICE_KEY: ENC[AES256_GCM,data:hzjJXWEz8+TJl9c4qmbsy2B6A/hGfLkqP8+MfqpHDGCLFYXbyWWYwdr0aSyw+PjNf1n7uOdoia6F7R8cF01xA+8dyCRTsMDFUUn+iHaaJI0oZP9vW7uvJ/dz9fJEYmoBD8S9RtlTJLlCsSGn3PGs+1dQh7GlQLhJAiU3g7weGUXYB6rEur3CHZG3KjrnSfmSPlNcT8rtMwDuQBx7YxFBnwD2L/AgIcojUY4/ZbDLRHy4ch4i,iv:wdJ6wS9PkVJsJ8TacY8sKxLjln94jpEgsfdyo3KZ95s=,tag:xms4jYwepsPZdjd84Y7y6Q==,type:str]
    CADAM_DB_URL: ENC[AES256_GCM,data:Uqwz+T5CRriJufXm6KxHkhmcnISAvK1AEtn6XQynR2M358DhUhNkMFuj1agPm7ljweZQf9XKnnZOHHMWzvH3CNbeAMuKdtgufzyP0izKeZI75TG+OuFgNjNPRfCrpX3SlmrhnpUto3g3Z+2D,iv:/UKPnVJJiWF83sdJu9MD/SbhQ5cAvTnz8dAzVbgNAMg=,tag:g4NeKfp9PhzYbcpaHpeAOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TDhIY1NpNW5jVTFEbnhM
            aHorc215eFNoL25mTUtnNWJZY2RpbFpaWkhRClAzYk0yN1A1YXFySnR1YkJpT3Bq
            VnRrV05YQlVVNjhrWG9aRFlFbStteG8KLS0tIDk4WFRia2tlZG9RUm5UYnJaVlRD
            VTZHLyt4bU1QbG9CQXRuN0VhN1JpL1UKTcmmZrCROAQX0ivmGemD8lxbp0lKjOtz
            2pZiE4szocnS0frGz3uLccfh9bMm2dIpniovED+JjQCfByoDk5Ir+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T16:43:36Z"
    mac: ENC[AES256_GCM,data:f1SPhHl4x+dsrKD5b1x2HUXwtesY8LKa85nkuRtnmb1ssFTyfhR9g7LhLw24/GJDn4s0dWgFubswgDYNSyA82GtxUl9vBsL8625aoqV1osgRBk81HLAhg8IbZ5841YhjmDcSqb8Q8/4xL4EyyF/YAOYSneqltc4mKC1N/wcdGks=,iv:3Srgs9ePa2G2IRApklCMPbei4b/mHGWaBYbi/Z/q2ys=,tag:Ehv9DZ1QhCAafsEX8UAVDw==,type:str]
    version: 3.13.2
