apiVersion: v1
kind: Namespace
metadata:
  name: cadam
  labels:
    app.kubernetes.io/part-of: cadam
    app.kubernetes.io/component: cad
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cadam-quota
  namespace: cadam
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"
