apiVersion: v1
kind: Secret
metadata:
    name: searxng-secrets
    namespace: webapps
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:PTpiRokvHwKIYSjeQ5cNuyseFTGsQfGPxcYOtYdTuVy4giU05XOUs1ebUKBojw7JrKr9kt1NA4AU2AB1Y8PVag==,iv:ipDecZhxTxHMZF7vi8hdXnVPJwYHWMvgc3GhBQgW9zo=,tag:lk1zjlBuWlzotGq+kIwoYw==,type:str]
    open-metrics-password: ENC[AES256_GCM,data:oVKCNRO8S/Iy/Y8dW0gv4Q1Ma0HqmRHBp7HIviG2F1s=,iv:eeUiIGYxplKoxUiSDEmd/v/JUBlEm22+w8MFYtgUxGc=,tag:XQk4lMGv9lYkiId2Y6aOdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWVZRc3B4d05yMkQxRllO
            UEJ3ZnhJVTJiQlhkc2ZTUW9US28rN3ozekN3CjJSM0NNb1pJRU9wbnJEdSt6Zlp6
            RVByaVErdTNTdVBIemVsNDhXSWtlZ0UKLS0tIDczclRncS93NTdoRDNNQUIxSEdT
            QkUyNVplcjh6ajUzUUNERnk5bTJlS28K9lU56tQrDLDQwg/t2M4XBSw2NIzwEhDW
            IJFHxWasM7JBHvbH9/bJrCDgPHwyMR2wbCPZimm4lVLLob3TwgVS8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T00:53:27Z"
    mac: ENC[AES256_GCM,data:1uylUn+739Hljulc3U2ebN0abif3kwsbu7ScRxJe2NFhi0BFhllzIm5dT4i+HTVrDTifekGNwqiTP/8B1tWTnUfW1eAzEQfX3xksPQmCaSW6bmQSqn0BX3kSEcsiSDrMQM4Kb60YakMble77UiYLFXK9K8jx/q0aJIMz9SPt3cs=,iv:r2G5aOoWRSc1XgebF5D5f4jLpi4uekw2tZjEEIO2M+Y=,tag:B3QLhxzj644Hpw2ImMk7xQ==,type:str]
    version: 3.13.2
