apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: email

resources:
  - namespace.yaml
  - postfix-relay.yaml
  - secret-mailgun.yaml
  # secret-mailu.yaml — saved for future Mailu full-stack deployment
