apiVersion: v1
kind: Secret
metadata:
    name: mailgun-smtp
    namespace: email
stringData:
    sasl_passwd: ENC[AES256_GCM,data:TSzAjl9/wsCorC7Cp+Tp78I9fYL8SheYhwHW+wkFuWQMBbexPIA1yLsfiDz9YIu07yrmmKQLfhfDJHz/6RrVLN2YV9ABLa94vRZD2t5lp35mswZD3S0JJSo61Z26x5xEwYc=,iv:J3KpYUOpPaTNBKwQwEyWGPgz86TRhACbhYXz9rNRzos=,tag:4qyEx2CwqoZLg6uTLzqJ+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UEV4VzNNcjdyKzdCYUY0
            dDFrcnlCSWFOS0hzYzh1dDBUZm1jM0tlM2xJCnlxbE9GQlVDbGlvd2lJSHhrMEov
            ODEvRVhoWGxqZ20zWEF2MU9mZ2hFT2cKLS0tIHB0dDgybHNJbXZJZTNvVkdPOWJZ
            SW1JTS9waHRjVHg1S1RVZktZSFN3YTgKi0v2vHSkbrG1p2Dc8CRXcdXWwxxhxivV
            p8Mqm/p2VqDRXaJlIPF4rfnoe3CEadUBGuXFmWmPP697l0YojmSjxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T01:18:02Z"
    mac: ENC[AES256_GCM,data:IPOqnbm4x5oXdNVuWaC3hMBeIZ7BKZ7DhsV52vG0uxEqlxtIqwrl5/Oql0l9HcRI8uR2IHBBcVRQgmWSTe+nJF6a9m/jfqlwbXRRQxLiJQkv8euDP3sGsgNImd0SgAKtTcJwxMepICRVku6+08MWWhDGJEeKOyFfW7TgbOAiKAc=,iv:1sEyuxZzOk1CJMwfBeaFEdRkdMvo00XpHfJsLBbuMfE=,tag:2+mBSvHPebfqKHWaH8YKtw==,type:str]
    version: 3.13.1
