apiVersion: v1
kind: Secret
metadata:
    name: mailgun-smtp
    namespace: email
stringData:
    sasl_passwd: ENC[AES256_GCM,data:UZVpq6hSv7IzbzKIZtEK1zmwpSIMg+QNuiYfF7yCi6K7Wkiu2yJIcmYbaLZdF37j0yuBd1GkRoEAWIQIeiSg2r7PEwSgTtFcAAp1zUwg9b0d6hruWfkHT7L3kYHuouXBn3c=,iv:yOKNPEBfLBjf1ZFPqR7Q/WNNSlwmjo19rYlaTprmhso=,tag:V/uZmWpHnN6JB0BxAVPb9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TmpxZWczK2xvV0lJRVV4
            cENYK2dMR3QzV0lZU1VxdnJaeFJ1ZzNoZ0RFCjFkWFlRZ25WZll4NkJYRUlTL0Rx
            bklESkhHT0d6WEZBcW8rcEllYjJ0WVEKLS0tIDIzVUdhbmU4ZVVhdVl0T3FQV2xE
            aGtmV3puYXpvOVR2Y0dMd3RwczYrNm8K2ZYfsNcPCQNo3eNIwBS5LMWGSwxvQRWZ
            Iq6D9GcT/FuGNdmzUPQCQk7ta5CGw6pEqaoD5pfDCS9kOGCioTIibw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T14:28:16Z"
    mac: ENC[AES256_GCM,data:iaJZzfKVYhX46hJ+NFJ+uK21V0nH7vLqKJ8xcD3mCjNYO6jWE8rw9OSUxwRFbPEpT3csU6OGG6PRjONCmiCwv0r4eGCRPNgDVhgifnYAtnKOABQtcwetJqOvfgAaaRIRAD4PXXR18B5vV0yJyBJUzRjJ7UrmX7hnloOAQuzsC3Q=,iv:b/+ujEBwarspmLzO37CgKS+0kGGhCymd6EfdDieTQOc=,tag:3kEWCT7+k5mQ104sy9HrLg==,type:str]
    version: 3.13.1
