apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bumpmesh
  namespace: 3dprinting
spec:
  secretName: bumpmesh-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bump.becklab.cloud
