apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - certificate.yaml
  - secret-user-invite.yaml
  - secret-ghcr-identity.yaml
  - deployment.yaml

images:
  - name: ghcr.io/yappingboy/becklab-user-invite
    newName: ghcr.io/yappingboy/becklab-user-invite
    newTag: latest
