apiVersion: v1
kind: Secret
metadata:
    name: ghcr-config
    namespace: toolbox
data:
    .dockerconfigjson: eyJhdXRocyI6IHsiZ2hjci5pbyI6IHsiYXV0aCI6ICJlQzFoWTJObGMzTXRkRzlyWlc0NloyaHdYelE1YTFodU5WWnBRMDlrYUhWNloyVjRaMUJXVkU1WFJIRkxOM1ZIT1RKYVRIRmhkQT09IiwgImVtYWlsIjogInlhcHBpbmdib3lAdXNlcnMubm9yZXBseS5naXRodWIuY29tIn0sICJpbmRleC5kb2NrZXIuaW8iOiB7ImF1dGgiOiAiZVdGd2NHbHVaMkp2ZVRwa1kydHlYM0JoZEY5cGRFcHZWMjl3UWxnelUyVlJOemRsT1hkMldIUk1XamRQYTBrPSIsICJlbWFpbCI6ICJ5YXBwaW5nYm95QHVzZXJzLm5vcmVwbHkuZ2l0aHViLmNvbSJ9LCAiZG9ja2VyLmlvIjogeyJhdXRoIjogImVXRndjR2x1WjJKdmVUcGtZMnR5WDNCaGRGOXBkRXB2VjI5d1FsZ3pVMlZSTnpkbE9YZDJXSFJNV2pkUGEwaz0iLCAiZW1haWwiOiAieWFwcGluZ2JveUB1c2Vycy5ub3JlcGx5LmdpdGh1Yi5jb20ifX19
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcngxRk9LdlJmZjZQTENQ
            eTM5MzZKeEZPMzYrWS9VeVh0UjJLMGZLUUUwCkZ5OHMzcDhFQkZZVG9YREFHYzBL
            K1hSRzRJRWpGRTdjaUZzOURpTlkweEUKLS0tIDdTQUNuR2R0eFZ3MUtxMTA0Rm5I
            VU1GQVNkRCt3S2F0OGNwWkhoWWlKdlUKo7f49PAg4M5ZZgCKFLd90aX4vcqHRmH/
            dXB/9piHT4+eLZoa4eMxfg2BNohWFCYqg6BDZYLte8ujzFfjp1E5BA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: '^\s*data:'
    lastmodified: "2026-08-06T22:51:44Z"
    mac: ENC[AES256_GCM,data:xTrvVDqLq3aoWV1+kXbVvxNIXck/H8+kKaPvxGg7yoyNlb9w14AUkuptXsiWaOIxsT2JDEhiczkC6cF001N8TidnOmSDt0Ya0zOvYQ50MgnHhUTsa0nx0+BncmOoFGvDiY8KLYlSZPLiQE9TNgsEFJRzLHWzcZM+9/pOKMJMwLs=,iv:4YWfAbwKcHsrr07R7YIO0TmT93ERR6juDY4QQNxnI6I=,tag:de1UGnrTtrDRCUnGKsjBGA==,type:str]
    version: 3.13.2
