apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: identity
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Lz6uUjR8IANm25QDbdP1V08DA6fBSVIhQUUKqOMI6yp8vG2Bl8ENzXbjwNRUTvfpXpmpaPj7MnWYIv628cDqkfKbQlL8O9LxEwW4H50AZhRvSj1XBjad+NomiZuZY9Q8ffD6L/kvMqBXOn1o50VL,iv:/ZoKUvv0/SmuSepiQaCq18k4X4vGOIlm+z4kkBBPhnI=,tag:rXhz/wMDb6lHQOrUYMWOSQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVd2dQQWNNL2ZSd1plZm1u
            WDdXVUl6NEtPdnhmdlgwaHM2bjJETjlzTUVnCmNSNlprTy9DSXg2dE14TXlJVkQr
            ZXFJOW1TRWZwdGRPeUpvV3pMZkM3N00KLS0tIG1sb2V4RVFiRlZyTUY0YzhkQ25j
            QzBUM2lPTXhLdXpKZVY2N3ROMW9hcVEKDoKGxan6UKAKVslL91xGLYR6PwofwUZE
            LqgOz2sJfCDRQL1wvEpfPpnBNGbWEHI4CqJk0NOAReE7ug93uXV4Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T13:15:44Z"
    mac: ENC[AES256_GCM,data:nwanpzzrgO2nouqnSxp0LWKc4mOf+wQ0F7lJtpr3YvA1Hfu4OLCRlp0XUlovawLeuC3BmdL9rFwXBq+CCrHnHyiEp5MnAJSR60Kqs6Eq0NXqoFdpRT540M0zy/G1sXsOlwVhu3T51ZpF4qAdX3i0m1dOhWG8CUJWjwP3MZFyF30=,iv:/F/ItRnjHgyrp40V3828r2uhWKH0t36wNso6wLIraoY=,tag:Kzlb9QrGufbE3EPYsTCEQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
