apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: toolbox
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:FiGIkGlqo22EvB16el8CS/xXY4NeQxFN8RQi5zwz9/WmLDtjw1YcK2855YciN/+xzVqRJrOwt7qbB9lqm5ym7MWPgTNN7mJi+4j1/LMET5GqJZvw8YWrlus94vVtxu4qmmbPSzXIciAh4pesTaw5,iv:zjUyazFFm6I66JzLmquGfVKKGECsBoeCC0k1ILoGBGs=,tag:le04aJ244xWlKyVxh7Q3rQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad2pienZDODMzYzcyZ1Z3
            eTRnN3RUSjhkeXVJd2xUYm55bEdhS3prOXpNCnAwN05VeHN4NkZLNjhEZitDcHBG
            M2llRm1qYmJ4VWt3UFYvUnRnbTJsZzQKLS0tIDYyUWl3QTJybGRDR0VuVy9lSE54
            M0xENVpGbDNmZ05xMDgzZGN6NHNVV2MKHPpzaZWFCW8iMLUHUuBR5EojnoJi9B5P
            1hlkoQUzDS0LiYdQ5QH2T213hWk7MAcwpfYReVcaJTObQIDEfKRmSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T13:15:44Z"
    mac: ENC[AES256_GCM,data:gCF95BNbHniPTeH+JZihXAbjH6cfE26ZCnBkPERMBmLBr2YNue7OXkO7N+cjai3ODZv06ajTCNwaRlzc5GNc5zugV4Nwsci9BAX7aBjdAzmwWaAO4Y2jkNXdp/pVilEOPZM/iq2Y9mCKt/2scnqnZ78NXtSCe1/Y421H5lBqHjk=,iv:xO3UwJY62P/B4N8iLlZCaq4NNZ41Sb+8URUdiu55iHY=,tag:PzpqCsxy9rG40tH5JgIhlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
