apiVersion: v1
kind: Secret
metadata:
    name: ghcr-config
    namespace: toolbox
stringData:
    config.json: ENC[AES256_GCM,data:rxN4sCKPislDh8qs2hjaziSHEEfKBrfeD3X6wjGX3lcfOo9mQtLMXIZYE/9+yF1mfWGkbhIp/J5v/MKP/LYSX7D7wTm2LybElAbcXuQy6zdxietvrYBuukTesDfQY2E8Nen+M7rz8En1HCzUq63pUq3RpKscEDzmkAGbT07XpwswZA0XI7vxESr/DwiWXSLvzlN0Uw==,iv:hgynOiRyrbJDk9V5in9wUquPIkwC5PyNyGWvGyucBOk=,tag:pIpz4K3pI0EBcwy/TvzsUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVG5UODZ4T3IySkhXdHFo
            WnI1Z0xYcGcyVHlrWEc2cG1xTDZrZFRaMmk0CmVpb0wrb1FDc2lmVTNwWFM2UURs
            cmNPUTlNQlU3cktPTUVuRk10NE5SREUKLS0tIG5kdUg4VjhJSWlmTHAzeU9xOEQv
            dEhTS3BJQVNzWlMrZnN1NldMcEFkQ1kKWLeeyouVc5MmAlHxBlRl9+4c4xYE29nf
            RMyKaNcStZoph6zi3wSD+gXSgWF2I797EPl4qL79OkB1hIdvXczPOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T02:57:36Z"
    mac: ENC[AES256_GCM,data:1arRlZ5q+Oa0tbxq0LJocgCJDFex1iGuPRbcIngAauzLSjNP7ZdGSuS/JgzVeypPoSnXqPbExPu+xYFWF7xrHwE8AWPJdSP1/ZqRZdcOMlXgRb76cJBPy8+gm8xEZjcfkWwrFt5c07b9M0frQGl++za3e1uKZ/WjWBk/dS5ZdCM=,iv:xWVtiSjMra8AWKcYNtX0/cEPvkQLs/Aae2wkS3R2kuA=,tag:qalK3jKjm9BT1OnMylnzPQ==,type:str]
    version: 3.13.2
