apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: identity
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:SZYRW0VTZtSDV3LHVYSqiYaTVkZ2KufrvBKjpUhM/MNhMGjQdlvRN8bMi99lGm/hTyy5xYVZEosFQ8hfgwnvxRPAit0jgaSBuxdKeBF3eaoGxJTpwm/WeZECjKiFQ+TlK9SfXv17BiAOBh99s88kQ5hCrMPNo9BSf9AKvmzYm7e4ytRE0iR29wjCL+pmwkLIVnF19Rv/os33RO0y36vAF2dt7mu4p6gtgL9rK+YetswUVDge13sIzAIdBINlgvyipRwphi6GgqPIbXbk,iv:AYbs422LiuyxqJTU8xpIsp7ntFXGWuXykoiyZ0u3U7E=,tag:iZeYzQ5xk4G9d4nleDdRLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaktBTVcvVStjSXpjbWxF
            eDIralJpcFZYYjJWeEovSjdtM1JWTHBRYWxJCkcyYXJHazZaVTFuMDY0NEk3U1pY
            eUVlc2dhV3R6RUl4NEJaZlczRHdlUnMKLS0tIFUzT2pXd1hsanVJR3hzeDZ1QmVj
            bUVGZ2ttWGRma000eFNpSXZiangyWjQK+oNek83WuBU6zU+35FfDG08VCOYXp8dL
            2QR6VEGs2wql2jGTp32Kgi1YXFefGSBb3RBt5Heu+jR4swXtGRZgJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T01:50:54Z"
    mac: ENC[AES256_GCM,data:j9/7wdVnxTxkI9qVApjXGk91PFzeEegTqJkni2cxGpxNPecPrfxAnEhThC0ZDzmzWWJMEHwp/7gjGnjm4YH1NXsJlWul8XJk5UzFx6Db6g6v2Nb+HZdBNsgWxeF78C1z5NXy41BxHrV31hpGAcJnrUbiXkl3htQKN2eiB0xWirY=,iv:Rb3DIdKaiHIqZ78hCbYnFT3kZ1P9AGsMTBvL/Q3NCsk=,tag:sYhendZDIuXObqiyHJZ7qw==,type:str]
    version: 3.13.2
