apiVersion: v1
kind: Secret
metadata:
    name: user-invite-secrets
    namespace: identity
stringData:
    flask-secret-key: ENC[AES256_GCM,data:cObgufBKxECyi5oUQRDCrq3v9YmQNMlsimICYYEN0/Of8hUZz5cWHo9bgDpkOWH4Hr/hpiKle5d9VO6izDzudg==,iv:3pjiEJmGkBtd4x9uWxwmePAZFHD+EckTR0p0AN+ehVo=,tag:LSyD16mjuuous7yaVJtTFg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UG9tYm1KM1c4blMxTm51
            NStDc1h3V0VnNVEvRFFlUnVzajM4RTNnVWlFCm43VnhJWWswZ1FLcENFSmpGM3dy
            aTM0RTdPL1ZLbDI0UndGU21VSy9tK1kKLS0tIG9QVUYvelM2cit3YjM0cVZWUVVJ
            M0k5K1dQa2pFSHQ5aGcxSzVhQ0JVd0UKpj7HGY0q8aJuJvESRO6A5t+eifTTAP4c
            ecLEBYAGkoIgE7HCSElj3rWinMzAgIRjWjjSBjQKTPtk9nD6mGXsSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T13:15:18Z"
    mac: ENC[AES256_GCM,data:WRbSAp+N1Tl+oWCTBak/QyqDkB3kMdUWsBaXFn0+/VP6NaeAw6aNkxYb3O7JSWUGR3JsnFmQkaAHg62UHaMs/SQIs3iuU76yemlZddGdHVIIPj2Ic+VjJsKgoC6bc2yh4IDMl31LHYWQ5heWGrBqmF40ZW5TZpj3r+O0vCZOlQE=,iv:nLzW9/T9goeUApro+AVIjXMaXY7HjMGgGrLRQijRtnA=,tag:/2cUgKlUnZyC0G6ANARKog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
