---
apiVersion: v1
kind: Secret
metadata:
    name: user-invite-secrets
    namespace: identity
stringData:
    flask-secret-key: ENC[AES256_GCM,data:yYxM9H0x862Y36tzePJmDAv/53NKjAM50E29ks0OAzA0+4b65DK8inNVIwZr4QJ3vp7LEVRQsB6a7g8Az4NzSm+W,iv:/O+2nml3Ss0jaLPo,tag:duTvr+3QWSldUQY9Phbbkw==,type:str]
sops:
    age:
        - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSVMwbHM1UTJnS3ZrUXRP
        VmFCV0JweHJGWU41aXZJYzVLSUFxT3Z6dlhnCmRGVnVpS0M4V09GNGltbHFzRktX
        WkR5ZnFzMmdQaHZITTBmMFY2RkxwekUKLS0tIFEvWUc2S2Y2M0RCdDRmUURUVU9U
        L1ZqVjI3VEh0RHJvRG5Sbm94c1lCemcKZBVj5OHpX4DA6bMhZ7IiZ/uvNfPTSNX2
        Ev1WLY7+qdaKLPRKO/phsqCwxeWiOdXRw2UjYGtuOyFlp0TtNf7UOg==
        -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: "^(data|stringData)$"
    lastmodified: "2026-07-07T03:01:10Z"
    mac: ENC[AES256_GCM,data:EI7GLcVILxchYTFFlXli9weLzP6OKKGarx6JTO8hV+ijxAmDbVMkW3IfpNZ3MbysGhLWiSUtz2PobI0XDejX0S2c1CpUDiIt7VM/6M7OK+DY4NfjOC1lENxVNwLIQ6I614Ccc9GzjMSrVCqVp/Pa1Xc68z+cT5hmwMa87R3Ocrg2iM1n928ngJZJSGzPoMIZkDsMeqd2fiRTiLuv+7sR9T5X8yqSFAvfKySM16ub5LF5sWznkIwJ0FDWIQBuXowL/lpUFEofOrNIfU399TVWgwaowk8hbhmtmj8pzK5MceRE2v3E5dKDjrPEMCyDehz52warzQdJFwhdURNKk+CoXJLhBeckPHLb7HE4PG4qaEGHbMb0o2ckY7YFLKQm25YDcymUxvSoe6ylNH/6A7Gl2RK4dX1wshHGTV/H1Uhq4AWX/+W4Bleb+72WnmV2U+BqMXQqajo5gqjD3Q3dzJ4JPRnmJVBuDKh88duXzvTry2uistwETH8uOBdfPb/Pt5E4fR4fCdPedeSQJuYi8D4KCKDjNE6xFIZu7JQfLEhx5a5dRSBvBylyBXfdvcYjmPBheNVSfJ2OIZpUZlxqd75E8pIygaGpHstMxq3XTinSugXct4KBicZjVgsXDL30W0eHmGqhZiEnGsao8MxuJfr3RltiigiprhLhuDNJFFjbAT9ADx2kZKGRjf5XO/HhtlxNd9riD+SmL/TIMD+WcjsC/A/u8/5CjBgbpk+KBixrfNNSMwY+9gthVnixDcfgC5j6+9aFpyYD2SiV5zOU/KY8BS/io4ZqKwzkIioRtgVpjxjvoDkjrC2KMHX4H4CUw8+9TYsMafTLGl6m5Eo2Y44xPEA0wT/BZLxlN7U2tF2BNNXyAzT8/JipkORAJzrqLE0WRiXLhELKAw464VT4N/REHY4Y20vB0DT7XOwaonsmtR+cN1OlbZ80lSoKTwLcKxaOj9ulD/4LATB2uNXhbCplWPY5zbjw/fDzLno0HWVVGbNqyAT42pmRjIJ+i+Vdv9a4W9+aLZwI23Kvuve3HV3xmi3XE8mriKPRnrFsq/bns/VIMyYSwlglwt22HWS1wqz+kbD4JtXCC/KpQieiVrcRi0eMU+EEjG0qaSmdokrKaec1HN9QX0GRWCcwWXNKwDNhcl8pxConRZEjUiThhxj+ERO0kPGktfR0U/e7pNv/bUDIxWLHBbTrcoJHrAWTr/TQ1nijqGmz/YXxdspeCTNGioTl87C2w14=,iv:hI3ZsB+nX3r3ixpy,tag:Cr34jtq1J/vYXzOwIira5g==,type:str]
