apiVersion: v1
kind: Secret
metadata:
    name: ghcr-config
    namespace: toolbox
data:
    .dockerconfigjson: e2F1dGhzOntnaGNyLmlvOnthdXRoOiBlV0Z3Y0dsdVoySnZlVHBuYUhCZk5EbHJXRzQxVm1sRFQyUm9kWHBuWlhoblVGWlVUbGRFY1VzM2RVYzVNbHBNY1dGMENnPT19LGluZGV4LmRvY2tlci5pbzphdXRoOmVXRndjR2x1WjJKdmVUcGtZMnR5WDNCaGRGOXBkRXB2VjI5d1FsZ3pVMlZSTnpkbE9YZDJXSFJNV2pkUGEwa0t9fSBlV0Z3Y0dsdVoySnZlVHBuYUhCZk5EbHJXRzQxVm1sRFQyUm9kWHBuWlhoblVGWlVUbGRFY1VzM2RVYzVNbHBNY1dGMENnPT19LGluZGV4LmRvY2tlci5pbzpkb2NrZXIuaW86e2F1dGg6ZVdGd2NHbHVaMkp2ZVRwa1kydHlYM0JoZEY5cGRFcHZWMjl3UWxnelUyVlJOemRsT1hkMldIUk1XamRQYTBrS319Cg==
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcngxRk9LdlJmZjZQTENQ
            eTM5MzZKeEZPMzYrWS9VeVh0UjJLMGZLUUUwCkZ5OHMzcDhFQkZZVG9YREFHYzBL
            K1hSRzRJRWpGRTdjaUZzOURpTlkweEUKLS0tIDdTQUNuR2R0eFZ3MUtxMTA0Rm5I
            VU1GQVNkRCt3S2F0OGNwWkhoWWlKdlUKo7f49PAg4M5ZZgCKFLd90aX4vcqHRmH/
            dXB/9piHT4+eLZoa4eMxfg2BNohWFCYqg6BDZYLte8ujzFfjp1E5BA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: '^\s*data:'
    lastmodified: "2026-08-07T00:19:22Z"
    mac: ENC[AES256_GCM,data:5EOvcDuoK+TrjNMtDwpfxY38yGTn1UialnokU+IqvxK/Ca+jmHzKbZinUu3YLBdAXxiMifT0iHF8S1FC4MY4eq7EYykOBEq2dA7xRPS00JmR6FIRNomwYOa+LZbcmJim1EISDDOxenlWh4Xur9Nx3tv7leVqaQqJsj2JuYBVTak=,iv:JJl6pskOcMKvF7yvzDMu45HD5GPcRyxWPBxOjKr96dk=,tag:KRg4pWtXHKVnvpG9H0SLuA==,type:str]
    version: 3.13.2
