apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: toolbox
stringData:
    config.json: ENC[AES256_GCM,data:BQEr4rxuPLDAbL7SUwcaVz3yojg874QXRQQ4OEeUND6sL7+kK48mK81EUqUPI3h4HbLHA2Y6Aw0nSEJ99B8hiLE2gPm5ML50KARDnT04Dj0uutaO06Nac8iazYAysBUWQIyuTsCI9TORnYbR08XUHfJYb761uFtMs1LPco3a/e7ONaY+gZzPiiPnE2+4tF4/Y99+,iv:X/tjA/6lT3Ed1yfnwposIZQqzWatXLyn8xgNN4jIB5M=,tag:22QdKJZOtzixOW0UW+x0ig==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFc1NSQkNHOFpHZFlYeDBI
            ZnR3SGgvWVZCdzE2QldWMjk1Qk8yRVF3cFV3CnNXQ1pPeENXQXRmUVNrZWpKQzVT
            NWhHK0FBSms0UHZBU1ZKL0VHZm1rbEEKLS0tIEZia0UzTS9NZDc5VkVUMnlxM0Qv
            SlYzeXdpdURJdWltd0xiWjdTcFZoVzgKXVHn6e3Ci+F7ntSsBCfAF6zq4ndYztX7
            jOt2IOjRMFEUb1izfktLuDtO9Pof/wF+2AlFJ/3HcdU0j5a9I675Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T14:00:15Z"
    mac: ENC[AES256_GCM,data:7Dw5PHu+sM43LEudm5WqjXhYQQDl/n3ATqGL+ugUVjoOxfPIqRkoK8lXx2CKTxPRFlcQOLZixhf1LQIhfC6Lb05ACLaFQbjdNC6gwYLRUKLHAHTtZwZrJUplSygzm0btCyM4KQn2c4ikCvHbDs3rEyOUUa40ZTchjBi8mfkboyw=,iv:ZN7fFaYn4pVeImvN+qQQR8dzH93pmyAj41DdEiQcIfQ=,tag:eQNHoET2jAaaxKlTSscErg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
