# Auto-split from cluster files
apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
data:
  recyclarr.yml: "sonarr:\n  sonarr:\n    base_url: http://sonarr.media:8989\n   \
    \ api_key: !env_var SONARR_API_KEY\n    delete_old_custom_formats: true\n    replace_existing_custom_formats:\
    \ true\n    include:\n      template: sonarr-quality-definition-web-1080p\n  \
    \  custom_formats:\n      - trash_ids:\n          - b903040092ad71c296401d6e9c37068c\n\
    \        assign_to_quality:\n          quality: unknown\n        has_to_include:\
    \ false\nradarr:\n  radarr:\n    base_url: http://radarr.media:7878\n    api_key:\
    \ !env_var RADARR_API_KEY\n    delete_old_custom_formats: true\n    replace_existing_custom_formats:\
    \ true\n    include:\n      template: radarr-quality-definition-web-1080p\n  \
    \  custom_formats:\n      - trash_ids:\n          - a783bcb78f758b1e92f70384775dbbc0\n\
    \        assign_to_quality:\n          quality: unknown\n        has_to_include:\
    \ false\n      - trash_ids:\n          - 0e0aad085f8570b98cb487ef7922a90f\n  \
    \      assign_to_quality:\n          quality: unknown\n        has_to_include:\
    \ false\n"
