# Auto-split from cluster files
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secrets
  namespace: media
stringData:
  sonarr-api-key: ENC[AES256_GCM,data:9u2+NG843SRt,iv:uLM2sq9Kj9gg+u1cDVFaOGV4DtIEthkwpzYtB4H7S8g=,tag:LHI2CDrKxzLy6kObxy1DCg==,type:str]
  radarr-api-key: ENC[AES256_GCM,data:/rRXIm+P7gcF,iv:7KlMhR7xMBOhwkSM43AcEdAj0E4gjASdEjkfnFWBzRU=,tag:ZnFqLSXyUf7cmrqOC0LinA==,type:str]
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa3RGWm4zQkh4RC8yV09E

      RmxhWStXZnBPc0hld0xrUkNHNWZZZFI2dUNjCk8veFI3d0VRT1lhS0gwd1hobGkz

      dGVNU3RzWnd0MUVMbW1VbUg1M0pyZVEKLS0tIE53ZmFZU0dUYzhtY09ReDRiTXRp

      NHBnNW1jK1dKQW8zQndoS3VuV3NGRlEKOSFm8oPXJoObmMM8d7fPzHLbyb5IJPYF

      ege1mrdigWChgmPI0BrcKHs+WI6WXv2yqIRj04xhogo9FE8g5kgZ2Q==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-05-17T17:37:32Z'
  mac: ENC[AES256_GCM,data:JNtAp44ZMvExwVU1lQlYDFjrLg18DM6PkcKazLTZ8vkxuAaRC1DRUa8Zaegquwu4eb7Ogx0MqlbTNPpRMDw9em+2Kx8VynwTYyEFu+iKyGP7Wdyvy3IOHLdcbJ2DhhbwqDmNfgXtXSxbHKe405i2Ioy+2oOXZauZGQMQL1CS78A=,iv:Q+rUDzHRRptyzlH/t68muhtUkMZwCG5o5shsoMRi1bc=,tag:k+QThMhgeRpC8DwdFAx2mw==,type:str]
  version: 3.13.0
