apiVersion: v1
kind: Secret
metadata:
    name: tooljet-db
    namespace: webapps
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:L3iHOUi9qg==,iv:mhSHhUhCv+tsBJ1QGeGRgQzvFIOtbgBuQwWsCEAazpk=,tag:IpE83s7jniZd3ejZNTzMmw==,type:str]
    password: ENC[AES256_GCM,data:HaCLmUNjRoFXmYguXGFTqiIPjcN0+KTQ,iv:/6AFHcTBqPCXU7ZxuCZvaO6piBi7U9bodc1KGktE8aQ=,tag:iBhj6SQ2khAkeloUhyyMJw==,type:str]
    database-name: ENC[AES256_GCM,data:MoySlvVf8CWqGp3FIjw8gE37,iv:zvjaDTSAwgaDZFYAH2nCN8k9821HXr3BfzriiCZFWvk=,tag:IZ3QBlZGd8kxRjiD4cELXg==,type:str]
    tooljet-db: ENC[AES256_GCM,data:H1tKnfUkrKEW9A==,iv:LlIbj8iEGhHLDwQRRv3C2polHA5DmUkOD6tcey3bbk8=,tag:DjIe4iNU1fVfpEk4weMoFQ==,type:str]
    lockbox-master-key: ENC[AES256_GCM,data:hSrLHz6S2SfP4puN0Zbf+c+ki7plf+GAbww7qGASpUPvFHHgnGW0bv6/Zz9EWsI7eJIzazF7+ZuhlKLMHF3ijA==,iv:ofO+x1JFH1XE4aW/e6wDXYgbVA79orhx3hFGWX9wTgc=,tag:CiOoL46pMrCu52/CFz+GvQ==,type:str]
    secret-key-base: ENC[AES256_GCM,data:22sp9NcuTUAjk97WY5JTXHptVIdb/MYRZZxWoe0t7v0D+L20nwbf5tsqFPzDUxmdRhEGov0JdE3KWANELSuyrwRxb0OJ7hPvU2cDkpbYDdHx4b99iU8ZAyJ/SaCibZAte5JFqkAZMeDhU6cIWezy8gxtHlbyXvn3iMNMxmH8lqc=,iv:SvhGdTmxlnOzFhJssXxA6FKh0ylEQJc95pUCuRRg+V4=,tag:be4jTn4g899UrFHOjLMTTQ==,type:str]
    pgrst-jwt-secret: ENC[AES256_GCM,data:B4fqOhUXzcwM+rTncC8OZxfX+n9f55m3ckYA9fZ/9CO/R71WJwwZZhjEnTq/jyXK0+1Yh5/4a4P1OnS3aqWwgw==,iv:/9ig2efmaEhcpP7CjF6coIdluQAu8uwaTiAoWOJNZb4=,tag:g0zqMA3jXssOm3imAzAvEw==,type:str]
    pgrst-db-uri: ENC[AES256_GCM,data:rxsnC1RXjoRA2MNGWvAMAo/wd8VVNCD7XXamR2AlOrIdTh07aZsuITcBbmtnsRqDpFAyXGRZ4aRhGw1TWJyBQfX2NK4dNQzzyWFFJjyCcUgH+GnoQyoMOLg668C+TOVh79ucJtO2,iv:QxB8SRp2PVojVxO4RoqO8uB+vDx4RZLLYq2v221KZag=,tag:rL/8LFs+LtlVBke8OEomqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdVI3dGNEVkdYajQyc3dW
            cVVTaTR5OVRQbzV5QWY1L2tNZ2lFMUZuU1I4CjZ3MkRwR0JjRDQ2bXBXR3FuY1hU
            aGJXeDR3d1JGc0hXSE5pQjFMQVViNlUKLS0tIFBDbUorZEVyanFqb0o2a1V1S3Vx
            WTNuN2dUdk5BcGFreGh1MCtWd1NpWmcKlwixvV8lGDCz6z1hj5JBR3xk6NNs9IqE
            phgTsMa4EoLbPmpH4g6nR3yhnbNmH1XA3DfzS8cuiizh0pMgvBZooQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T01:57:53Z"
    mac: ENC[AES256_GCM,data:SiHo/Q6eUC5ivlB/CPd1g9H9wcGF9r/OTtmc32Ib3M4oUC0p6XcPXOBpAYEqf3duFE/Snv8mqRBAROxHddAZCar02RHoQz8C5Lo0xNZgB9dV6iF1WXKQ9F8yVNv9Fz53dm87CUFoc4XvL/vwAFoAMSnyVv6nQX4tRF0dz/D6zJE=,iv:mehQ2nXfX3vamM1IZfGZMOuw5l7RQI2j6o+0du7V5HA=,tag:lkDE26NBMmwIY8vzQemIJQ==,type:str]
    version: 3.13.2
