# Auto-split from cluster files
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: silex
  namespace: webapps
spec:
  secretName: silex-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - silex.becklab.cloud
