apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-sources
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux/infrastructure/sources
  prune: true
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: beck-cloud
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux/infrastructure/controllers
  prune: true
  dependsOn:
    - name: infrastructure-sources
  sourceRef:
    kind: GitRepository
    name: beck-cloud
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-configs
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux/infrastructure/configs
  prune: true
  dependsOn:
    - name: infrastructure-controllers
  sourceRef:
    kind: GitRepository
    name: beck-cloud
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux/infrastructure
  prune: true
  dependsOn:
    - name: infrastructure-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
