apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - sources
  - controllers
  - configs
  - csi-snapshotter
  - traefik
  - cert-manager
  - identity
  - security
  - llm-stack
  - velero
  - rancher
  - media
