apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sources
  - controllers
  - configs
  - csi-snapshotter
  - cert-manager
  - traefik
  - identity          # includes email (postfix-relay)
  - rbac
  - security          # includes trivy-operator
  - crowdsec          # Crowdsec + Traefik bouncer
  - media             # includes qbit-gluetun, spotweb
  - monitoring
  - velero
  - opennebula
  - webapps           # bitwarden, cms/directus, landing-page/silex, affine, homepage
  # - ticketing
  # - support
  - gaming
  - 3dprinting
  - gridspace
  - micro
