apiVersion: v1
kind: ConfigMap
metadata:
  name: beck-cloud-config
  namespace: flux-system
data:
  domain: "becklab.cloud"
  ssl_email: "yappingboy@gmail.com"
  homelab_ip: "172.16.0.7"
  flux_version: "2.4.0"
  k3s_version: "v1.32.0+k3s1"
  cilium_version: "1.17.0"
  rancher_version: "2.9.4"
  velero_version: "8.0.0"
