apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: beck-cloud
  namespace: flux-system
spec:
  interval: 1m
  url: "https://github.com/yappingboy/beck-cloud"
  ref:
    branch: main
  secretRef:
    name: github-token
