apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - configmap.yaml
  - infrastructure.yaml
  - traefik-config.yaml
  - cert-manager-config.yaml
  - apps.yaml
