apiVersion: v1
kind: LimitRange
metadata:
  name: flux-limits
  namespace: flux-system
spec:
  limits:
    - type: Container
      default:
        cpu: 300m
        memory: 128Mi
      defaultRequest:
        cpu: 50m
        memory: 32Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: flux-resources-quota
  namespace: flux-system
spec:
  hard:
    pods: "8"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: critical-pods-flux-system
  namespace: flux-system
spec:
  hard:
    pods: 1k
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - system-node-critical
          - system-cluster-critical
