apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox
  namespace: media
  labels:
    app: homebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebox
  template:
    metadata:
      labels:
        app: homebox
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-100-11
      securityContext:
        fsGroup: 1000
      containers:
        - name: homebox
          image: ghcr.io/sysadminsmedia/homebox:latest
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/New_York
            - name: HBOX_AUTH_API_KEY_PEPPER
              value: "WesFL+mZSTT9ySmaLHWSEfO4LXqVYKffBTNReG75e4DpkbDXFTk+xxT+VmMhzY3W"
          ports:
            - containerPort: 7745
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/data
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 7745
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 7745
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homebox-config
---
apiVersion: v1
kind: Service
metadata:
  name: homebox
  namespace: media
spec:
  selector:
    app: homebox
  ports:
    - name: http
      port: 7745
      targetPort: 7745
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebox
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: identity-sso-admin-chain@kubernetescrd
spec:
  tls:
    - hosts:
      - homebox.becklab.cloud
      secretName: homebox-tls
  rules:
    - host: homebox.becklab.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: homebox
                 port:
                   number: 7745
