apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-100-11
      securityContext:
        fsGroup: 1000
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: 1
              memory: 2Gi
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/New_York
          ports:
            - containerPort: 8096
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media-movies
              mountPath: /data/movies
            - name: media-shows
              mountPath: /data/shows
            - name: media-anime
              mountPath: /data/anime
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: media-movies
          persistentVolumeClaim:
            claimName: media-movies
        - name: media-shows
          persistentVolumeClaim:
            claimName: media-shows
        - name: media-anime
          persistentVolumeClaim:
            claimName: media-anime
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - jellyfin.becklab.cloud
      secretName: jellyfin-tls
  rules:
    - host: jellyfin.becklab.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
