apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvcs.yaml
  - pvs-lvm.yaml
  - bazarr
  - homebox
  - jellyfin
  - jellyseerr
  - nzbget
  - prowlarr
  - qbit-gluetun
  - radarr
  - recyclarr
  - sabnzbd
  - sonarr
  - spotweb
  - swiparr
  - tdarr