apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvs-lvm.yaml
  - pvcs.yaml
  - secret-gluetun.yaml
  - secret-recyclarr.yaml
  - jellyfin.yaml
  - jellyseerr.yaml
  - sonarr.yaml
  - radarr.yaml
  - prowlarr.yaml
  - bazarr.yaml
  - recyclarr.yaml
  - qbit-gluetun.yaml
  - nzbget.yaml
  - tdarr.yaml
  - secret-tdarr.yaml
  - homebox.yaml
  - spotweb
