apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvs-lvm
  - pvcs
  - qbit-gluetun
  - recyclarr
  - jellyfin
  - jellyseerr
  - sonarr
  - radarr
  - prowlarr
  - bazarr
  - nzbget
  - tdarr
  - homebox
  - spotweb
  - swiparr
