apiVersion: v1
kind: LimitRange
metadata:
  name: media-limits
  namespace: media
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: media-quota
  namespace: media
spec:
  hard:
    pods: "20"
    requests.cpu: "6"
    requests.memory: 14Gi
    limits.cpu: "40"
    limits.memory: 42Gi
