apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secrets
  namespace: media
stringData:
  # Get from Sonarr: Settings > General > Security > API Key
  sonarr-api-key: CHANGE_ME
  # Get from Radarr: Settings > General > Security > API Key
  radarr-api-key: CHANGE_ME
