apiVersion: v1
kind: Secret
metadata:
    name: gluetun-vpn-secret
    namespace: torrent
stringData:
    #ENC[AES256_GCM,data:q3DN6LK5qFIkU7TN57zeK2fd3bSJzn9q+lw1IRQWa8FlWnNCltWI3oVSsHb/,iv:Ch2BfkbUVlaeJLCFwloTrcMk4DYIruRYkS+QHgkuYOU=,tag:cdAuai/oXlzdoMxOvR3JAg==,type:comment]
    #ENC[AES256_GCM,data:R8VKHllexxqwxs6/kOFHm8Yzd1OaXBIzfSdPAJSdSxgoLvvCMEwLmf3GTFdC5vMAnFbDkZF9RNcWQ41suLCgK1RFavZ9OcM5,iv:SrEbUHANOvQDaWlKT902AvI7h5dNeuuWMCDadtyjYdY=,tag:SJ5QkSmyjxAmASiFcEfErg==,type:comment]
    pia-username: ENC[AES256_GCM,data:xXIr9fCm7oQ=,iv:5DlyrkammIpjaxFQAWBvKpCyRP6/agz2TDZjIgiF6hg=,tag:ZHR7E72J3BK3GotcH21lkA==,type:str]
    pia-password: ENC[AES256_GCM,data:vm6iWxad0dUEWQ==,iv:bO2gpjYPQ+QVjBCLiliab3nVjqoqtryOhfXzsfEqiq0=,tag:IMDjgHpjL56R2/vsRdHP/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHekNUN0g1YWRNUmRyaWk5
            WVU4OXN5T2J1cWVsWUJrNU9UUTE0cjNmU21rCjZmSnlHMktzUjFKUFlWb2s2Z2JQ
            UXR4UkNyWjZMd0xmSFZ1cnNlNzhpMDgKLS0tIEtIUVJDeEpERzZaY3ZjcUI1cHFu
            dFBvR25EeXU0TktRRHZMcEZQclZpRnMKM5sPJi1Hdj/xjxB+GQ0iEXhnuxIvMKXT
            drnZtxCslsnqBZH4asiRWIqFczF/jxcbY4+IvLdfWhYMLwz5bh4D3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T18:12:14Z"
    mac: ENC[AES256_GCM,data:gxJ1du9MndAOGWOxrNEtYLhiVN6ab+5t67Vh39xA7itwZE3+J6yh8cTt3vaXgS/I9r4Doc8vvNzlS8aVDonLXNxlsV33KbxmiI4MBtpgzuK12nwGgAqhlz59anupO3hp7s8U9Ji//u1fEUWnYerjicoeLt3iRGleSmUm13c1qE0=,iv:jPpyCzf9Ip347YogPWNGKphyS8laHKQJGKr8FseWTGs=,tag:Hu0EAxx2pqjpYB8x8ChnjQ==,type:str]
    version: 3.13.0
