apiVersion: v1
kind: Secret
metadata:
  name: gluetun-vpn-secret
  namespace: torrent
stringData:
  # WireGuard private key from your PIA account:
  # https://www.privateinternetaccess.com/pages/client-support/ > WireGuard
  wireguard-private-key: CHANGE_ME
