apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: media
stringData:
    #ENC[AES256_GCM,data:A+hBHi/x/vMl/pTi1p7TfxqZCtweVz25T4y0JALEXl6cK0Z953hLQqDWRWkY3zCq8gtYrW+ZZ4pZ,iv:6NXVJTzX/4U72CdNzTDFz9XTVs7ydAyvO2vdyEEHBDE=,tag:ohjuU8DkDYt7FPXsKBgo4g==,type:comment]
    sonarr-api-key: ENC[AES256_GCM,data:9u2+NG843SRt,iv:uLM2sq9Kj9gg+u1cDVFaOGV4DtIEthkwpzYtB4H7S8g=,tag:LHI2CDrKxzLy6kObxy1DCg==,type:str]
    #ENC[AES256_GCM,data:2kZbIWlRkzbRoGj9zlDxzMWi+70qi0iO/cdXuURfhWmZ679lqilBzjHxRc0n99iTh/Mvk1ym9Al9,iv:tDVxqH+8Q1bEvyVokmdc7HC/JqW9G+xMfF78g/R1sqk=,tag:WeWjPjDCwpXsPlTkS6A4Zg==,type:comment]
    radarr-api-key: ENC[AES256_GCM,data:/rRXIm+P7gcF,iv:7KlMhR7xMBOhwkSM43AcEdAj0E4gjASdEjkfnFWBzRU=,tag:ZnFqLSXyUf7cmrqOC0LinA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcnI0enEyNFRKU1FRclpW
            Q1RscDBmN2VkSyttanVEaWNEdDV0S2xsTGxrCityUi9yeHdMcm1MeVpRRkNxdVZz
            dWdST0hrd0ZOWGJBbzlhb1B0ekxNT0UKLS0tIHpLWU5vaks5dVNjZzNpcm1JYTN2
            eWxHdk0zY0RjdGcyREI2czcwU0d1Q2sK+TgcCZkf4SOR75kE8Xb5KWO/MsiJkSLt
            elBTfQjJMmtaiIboIe7e3ja6teIeGtJmRSQlHDuE6iuaOqk6YiCB1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15f2mn6pl769c22z8hw6mtrsna8l7fehml4j0m6jn573cs9vahcjsdrxh20
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:37:32Z"
    mac: ENC[AES256_GCM,data:JNtAp44ZMvExwVU1lQlYDFjrLg18DM6PkcKazLTZ8vkxuAaRC1DRUa8Zaegquwu4eb7Ogx0MqlbTNPpRMDw9em+2Kx8VynwTYyEFu+iKyGP7Wdyvy3IOHLdcbJ2DhhbwqDmNfgXtXSxbHKe405i2Ioy+2oOXZauZGQMQL1CS78A=,iv:Q+rUDzHRRptyzlH/t68muhtUkMZwCG5o5shsoMRi1bc=,tag:k+QThMhgeRpC8DwdFAx2mw==,type:str]
    version: 3.13.0
