apiVersion: v1
kind: Secret
metadata:
    name: tdarr-secrets
    namespace: media
stringData:
    api_key: ENC[AES256_GCM,data:UrJXdeQX7ktfTJuioKi3o+UPSrUCJitBagMlQVSNIjlPt9Sge0viFv0GmHIXdSPCw0JmHUgWV2hQvsvR8aUBDw==,iv:4l2O/XuqTFKgWjJVNRo4rtJjVdkFrEp14b7MqqkOTLI=,tag:/CiY8geY/D9vcKAWeKoC1w==,type:str]
    db_password: ENC[AES256_GCM,data:56Socxw1A4VsmyLIDjzpvdju9EaAT/FMk1xnyO0RSnC4wWVOmrmZ4RzMKALmkG7W,iv:I1GkWqR9/BZf1oI9yl/g1L6/wPmP+gr7o/xuLvKLzbI=,tag:N7Wlcar73ZTK8hre3uubaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U0YwZFVOSXJNV1NIUHlq
            Ky9seGxpODgwZzdrZ1dPTWZyVitoeUczbkhJClNGcDFsVUU3MlFmc0NsVHVIR2FS
            dHh1YjV4cWRIY1Y5SDYrWUhtYk5TWjgKLS0tIHN1SDJhakdibHZXWjlZL2ppZ0RD
            bHd5UVFEcUZBYlZYYzBlNlZaZXh1cEUK6GGy7XCS1pANZgRHvoSrTwD03giVZSYM
            x43lTAbLnxhmY4aojgfs8oKlVB1SOmM+CiXphSce8WJKbIY/iP0C/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T20:18:47Z"
    mac: ENC[AES256_GCM,data:h4mtxCYFn7UAcJ3PSHLMPLU93KKwY0hIt3X2N5USLjkKE0vVC2OXq6vnKwaDpBDbtVc/kuclSFU1f3NeehCkXAPrDQFGpA/91C56vQk58FA3c+Y1AwZqc2LSCar4g5C39HZiGR4KAz9IesWjfnufdmenlu3iXzeQaLxc0vFK3q4=,iv:Wuy0oiiZXI+qXASm0MoMoMvigB7yjzGETBz3zhB1HyI=,tag:1VMFHZ26qy6/JKJcvs9RNQ==,type:str]
    version: 3.13.2
