apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: identity
spec:
  selector:
    app: lldap
  ports:
  - name: ldap
    port: 389
    targetPort: 3890
    protocol: TCP
  - name: web
    port: 17170
    targetPort: 17170
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lldap-external
  namespace: identity
spec:
  selector:
    app: lldap
  ports:
  - name: ldap
    port: 389
    targetPort: 3890
    protocol: TCP
    nodePort: 31389
  type: NodePort
