# Auto-split from cluster files
apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-filebeat-config
  namespace: security
data:
  filebeat.yml: "# Wazuh - Filebeat configuration file\nfilebeat.modules:\n  - module:\
    \ wazuh\n    alerts:\n      enabled: true\n    archives:\n      enabled: false\n\
    \nsetup.template.json.enabled: false\nsetup.template.overwrite: true\nsetup.template.json.path:\
    \ '/etc/filebeat/wazuh-template.json'\nsetup.template.json.name: 'wazuh'\nsetup.ilm.enabled:\
    \ false\noutput.elasticsearch:\n  hosts: ['https://wazuh-indexer:9200']\n  username:\
    \ 'admin'\n  password: 'WazuhSecretPassword'\n  ssl.verification_mode: 'full'\n\
    \  ssl.certificate_authorities: ['/etc/ssl/root-ca.pem']\n  ssl.certificate: '/etc/ssl/filebeat.pem'\n\
    \  ssl.key: '/etc/ssl/filebeat.key'\n\nlogging.metrics.enabled: false\n\nseccomp:\n\
    \  default_action: allow\n  syscalls:\n  - action: allow\n    names:\n    - rseq\n"
