apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-panel
  namespace: webapps
  labels:
    app: admin-panel
spec:
  secretName: admin-panel-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - admin.becklab.cloud
