apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: admin-panel
  namespace: webapps
  labels:
    app: admin-panel
    sso: "false"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`admin.becklab.cloud`) && PathPrefix(`/api/`)
      priority: 10
      services:
        - name: admin-panel
          port: 8080
          scheme: http
    - kind: Rule
      match: Host(`admin.becklab.cloud`) && PathPrefix(`/`)
      priority: 5
      middlewares:
        - name: sso-admin-chain
          namespace: identity
      services:
        - name: admin-panel
          port: 8080
          scheme: http
  tls:
    secretName: admin-panel-tls
