apiVersion: v1
kind: Secret
metadata:
  name: admin-panel-secrets
  namespace: webapps
  labels:
    app: admin-panel
type: Opaque
stringData:
  directus-password: "suCNJ5CtDdHEdy3Zhy6azwgG"
  kc-client-secret: "9lJwF6HKD8z2l8ft9qbheIGASgAZTdrr"
