apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: beckflow
  namespace: micro
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Workflow automation
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: mdi-flowchart
    gethomepage.dev/name: Beckflow
    gethomepage.dev/weight: '12'
    gethomepage.dev/href: https://beckflow.tools.becklab.cloud
