apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bitwarden-secrets-manager
  namespace: webapps
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Secrets manager
    gethomepage.dev/group: Identity
    gethomepage.dev/icon: si-bitwarden
    gethomepage.dev/name: Bitwarden BSM
    gethomepage.dev/weight: '3'
    gethomepage.dev/href: https://bw.becklab.cloud
