apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bumpmesh
  namespace: 3dprinting
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Mesh analysis
    gethomepage.dev/group: 3D Printing
    gethomepage.dev/icon: mdi-cube-scan
    gethomepage.dev/name: Bumpmesh
    gethomepage.dev/weight: '5'
