apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crafty
  namespace: gaming
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Minecraft server
    gethomepage.dev/group: Gaming
    gethomepage.dev/icon: crafty-controller
    gethomepage.dev/name: Crafty Controller
    gethomepage.dev/widget.type: minecraft
    gethomepage.dev/widget.url: https://crafty.becklab.cloud
    gethomepage.dev/weight: '1'
