apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: editor
  namespace: micro
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Image editing
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: mdi-image-edit
    gethomepage.dev/name: Image Editor
    gethomepage.dev/weight: '11'
    gethomepage.dev/href: https://editor.tools.becklab.cloud
