apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fmt
  namespace: micro
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Format converter
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: mdi-code-braces
    gethomepage.dev/name: YAML/JSON Tool
    gethomepage.dev/weight: '9'
    gethomepage.dev/href: https://fmt.tools.becklab.cloud
