apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hash
  namespace: micro
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Hash generator
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: mdi-hash
    gethomepage.dev/name: Hash Tool
    gethomepage.dev/weight: '1'
    gethomepage.dev/href: https://hash.tools.becklab.cloud
