apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: media
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Media requests
    gethomepage.dev/group: Media
    gethomepage.dev/icon: mdi-television-box
    gethomepage.dev/name: Jellyseerr
    gethomepage.dev/widget.type: seerr
    gethomepage.dev/widget.url: https://requests.becklab.cloud
    gethomepage.dev/weight: '10'
    gethomepage.dev/href: https://requests.becklab.cloud
