apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- patches/user-invite.yaml
- patches/bumpmesh.yaml
- patches/fdmmonster.yaml
- patches/manyfold.yaml
- patches/orcaslicer.yaml
- patches/spoolman.yaml
- patches/crafty.yaml
- patches/crafty-2.yaml
- patches/kiri-moto.yaml
- patches/mesh-tool.yaml
- patches/void-form.yaml
- patches/keycloak.yaml
- patches/lldap.yaml
- patches/logout-page.yaml
- patches/bazarr.yaml
- patches/homebox.yaml
- patches/jellyfin.yaml
- patches/jellyseerr.yaml
- patches/nzbget.yaml
- patches/prowlarr.yaml
- patches/qbit-gluetun.yaml
- patches/radarr.yaml
- patches/sabnzbd.yaml
- patches/sonarr.yaml
- patches/spotweb.yaml
- patches/tdarr.yaml
- patches/grafana.yaml
- patches/hubble-ui.yaml
- patches/opennebula.yaml
- patches/traefik-dashboard-https.yaml
- patches/affine.yaml
- patches/bitwarden-secrets-manager.yaml
- patches/directus.yaml
- patches/home-assistant.yaml
- patches/landing-page.yaml
- patches/silex.yaml
- patches/openclaw.yaml

