apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- user-invite.yaml
- bumpmesh.yaml
- fdmmonster.yaml
- manyfold.yaml
- orcaslicer.yaml
- spoolman.yaml
- crafty.yaml
- crafty-2.yaml
- kiri-moto.yaml
- mesh-tool.yaml
- void-form.yaml
- keycloak.yaml
- lldap.yaml
- logout-page.yaml
- bazarr.yaml
- homebox.yaml
- jellyfin.yaml
- jellyseerr.yaml
- nzbget.yaml
- prowlarr.yaml
- qbit-gluetun.yaml
- radarr.yaml
- sabnzbd.yaml
- sonarr.yaml
- spotweb.yaml
- tdarr.yaml
- grafana.yaml
- hubble-ui.yaml
- opennebula.yaml
- traefik-dashboard-https.yaml
- affine.yaml
- bitwarden-secrets-manager.yaml
- directus.yaml
- home-assistant.yaml
- landing-page.yaml
- silex.yaml
- openclaw.yaml

