apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- user-invite.yaml
- admin-panel.yaml
- bumpmesh.yaml
- fdmmonster.yaml
- manyfold.yaml
- orcaslicer.yaml
- spoolman.yaml
- crafty.yaml
- kiri-moto.yaml
- mesh-tool.yaml
- void-form.yaml
- keycloak.yaml
- lldap.yaml
- logout-page.yaml
- oauth2-admin.yaml
- bazarr.yaml
- homebox.yaml
- jellyfin.yaml
- jellyseerr.yaml
- nzbget.yaml
- prowlarr.yaml
- qbit-gluetun.yaml
- radarr.yaml
- sabnzbd.yaml
- sonarr.yaml
- spotweb.yaml
- swiparr.yaml
- tdarr.yaml
- hash.yaml
- short.yaml
- base64.yaml
- markdown.yaml
- resize.yaml
- cron.yaml
- dns.yaml
- webhook.yaml
- fmt.yaml
- qr.yaml
- editor.yaml
- beckflow.yaml
- auth-admin.yaml
- grafana.yaml
- hubble-ui.yaml
- opennebula.yaml
- traefik-dashboard-https.yaml
- affine.yaml
- bitwarden-secrets-manager.yaml
- directus.yaml
- home-assistant.yaml
- landing-page-gateway.yaml
- landing-page.yaml
- silex.yaml
- openclaw.yaml
- sudoku-meals.yaml

