apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-admin
  namespace: identity
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: SSO redirect
    gethomepage.dev/group: Identity
    gethomepage.dev/icon: mdi-shield-check
    gethomepage.dev/name: OAuth2 Proxy
    gethomepage.dev/weight: '98'
    gethomepage.dev/href: https://oauth2.becklab.cloud
