apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbit-gluetun
  namespace: media
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Torrent downloads
    gethomepage.dev/group: Media
    gethomepage.dev/icon: si-qbittorrent
    gethomepage.dev/name: qBittorrent
    gethomepage.dev/widget.type: qbittorrent
    gethomepage.dev/widget.url: https://qbittorrent.becklab.cloud
    gethomepage.dev/weight: '8'
    gethomepage.dev/href: https://qbittorrent.becklab.cloud
