apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qr
  namespace: micro
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: QR code generator
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: mdi-qrcode
    gethomepage.dev/name: QR Generator
    gethomepage.dev/weight: '10'
    gethomepage.dev/href: https://qr.tools.becklab.cloud
