apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: media
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Movie manager
    gethomepage.dev/group: Media
    gethomepage.dev/icon: si-radarr
    gethomepage.dev/name: Radarr
    gethomepage.dev/widget.type: radarr
    gethomepage.dev/widget.url: https://radarr.becklab.cloud
    gethomepage.dev/weight: '3'
    gethomepage.dev/href: https://radarr.becklab.cloud
