apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: resize
  namespace: micro
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Image resizing
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: mdi-crop
    gethomepage.dev/name: Image Resize
    gethomepage.dev/weight: '5'
    gethomepage.dev/href: https://resize.tools.becklab.cloud
