apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: media
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: NZB downloader
    gethomepage.dev/group: Media
    gethomepage.dev/icon: mdi-download
    gethomepage.dev/name: SABnzbd
    gethomepage.dev/widget.type: sabnzbd
    gethomepage.dev/widget.url: https://sabnzbd.becklab.cloud
    gethomepage.dev/weight: '6'
