apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spotweb
  namespace: media
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: NZB search
    gethomepage.dev/group: Media
    gethomepage.dev/icon: mdi-web
    gethomepage.dev/name: Spotweb
    gethomepage.dev/weight: '12'
