apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: swiparr
  namespace: media
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Media search
    gethomepage.dev/group: Media
    gethomepage.dev/icon: mdi-television-play
    gethomepage.dev/name: Swiparr
    gethomepage.dev/weight: '13'
    gethomepage.dev/href: https://swiparr.becklab.cloud
