apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: user-invite
  namespace: identity
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: User provisioning
    gethomepage.dev/group: Identity
    gethomepage.dev/icon: mdi-account-plus
    gethomepage.dev/name: User Invite
    gethomepage.dev/weight: '4'
