apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvcs.yaml
  - manyfold.yaml
  - fdmmonster.yaml
  - spoolman.yaml
  - bumpmesh.yaml
  - orcaslicer.yaml

secretGenerator:
  - name: manyfold-db-secret
    namespace: 3dprinting
    literals:
      - password=Xk9#mP2$vL7nQ4wR
      - database-url=postgresql://manyfold:Xk9#mP2$vL7nQ4wR@manyfold-db.3dprinting.svc.cluster.local:5432/manyfold_production
