apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvcs.yaml
  - manyfold.yaml
  - fdmmonster.yaml
  - spoolman.yaml
  - bumpmesh.yaml
  - orcaslicer.yaml
