apiVersion: v1
kind: Secret
metadata:
    name: trudesk-secrets
    namespace: support
stringData:
    jwt_secret: ENC[AES256_GCM,data:8Gjh5RTT9oOt5poPONRe3ZasYZ/BBFuHZUQbxreDDo/N667+nqlDKxbAqCU=,iv:m4IuvsJotkLwP1ma5XPQzErODO54SrOKiT+nuajRQf8=,tag:JnW0L5Kahbaw6oZcKIy0cA==,type:str]
    session_secret: ENC[AES256_GCM,data:nBdli7gizqsa2/N+0RzPQwTepjq1uwhKYMTRaWa/vlX8xJ6v7Zm8GgVzCp8=,iv:aK8EsoUmdQrbG4iy2P3uG5/gbMD9FV1ZNeewMpOY9FA=,tag:RPPQJr6ibe/OgRS5sz7rig==,type:str]
    mongo_password: ENC[AES256_GCM,data:h8hia74b2qGB88UMZml+mcheOIgxXnVRobIDBlikeY8=,iv:LUVIDc5+SoZknxktW0j7L/v62+6O9z46HuSv6BFCYsg=,tag:G7DIRgNzFKKNNQiIXjWd0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycTQzVDhiMGRJTzYzY1RG
            Rkdkc2hSWisvODRFZmpWY0xpWGNnbWxzWUFNCnBxMzRjVnR2Q1JoSXJVa2FMNFhq
            clBzeWVSeDVqU3ZjNFRQdzF1emZzNmMKLS0tIHd2RUwxR1ArZ2owb1Nka2hVOW9P
            d1ZkQnVubTBRTmpwZUJjK0k4N1VZMmsKB7ljz189cIGkx68cqTrbMqYk+BoV8Dql
            GgJ2Tvkx4HnIfA5eQVthWlBAhDkN8B+IJVDvV2PwiX357KdfNU3WSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T03:35:06Z"
    mac: ENC[AES256_GCM,data:lNRpiAch33IHeyCIyx7n1aXAmkberqUCf0gFaBL1j8lJc98kp7dR4TKfThHp1wIkhoKfWfg5qi3yTgOdej+/wl5B8L2wLv4JUj2S+paFZAkSACg99tVgB5nq8AHBzhv31hcE+AjBXWnw3G0hCpCgL+yOGzVXVgfBr6G17bLIpHA=,iv:2xzTbToGcgo1Mbzcu9fnXW2Yu5PGDNQA/nW3eWfTsQ0=,tag:WuBA9PBFL2v4QRe1dxGv8A==,type:str]
    version: 3.13.1
