apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - landing-page.yaml
  - silex.yaml
  - ftp-deployment.yaml
  - ftp-service.yaml
  - ftp-pvc.yaml
  - ftp-ingress.yaml
