apiVersion: v1
kind: Secret
metadata:
    name: vsftpd-secrets
    namespace: landing
stringData:
    ftp_username: ENC[AES256_GCM,data:y3LEA4Ci1g==,iv:20q7Rpag9Fw+7HHMP+39nMOUenHGN1i3E/6bcusl2HE=,tag:+rYisZBTmrFgv2b72TP25A==,type:str]
    ftp_password: ENC[AES256_GCM,data:X3sBU9q0WiZ0riIF,iv:EPygjPOUuuBSgit3YtFr8x8VOjw/lboGYNbVDOAzGTY=,tag:66r1iPrPytxn5BnfgEmFVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdFRnOHFjVlhmbEdBSmVU
            bWp2U2hJOG0yMEdoZDNDeElmZG92cFVjdmdVCndXeUd6T21xaUJ2dnlmOGhNMmcx
            U0ZDMVJGeWFjSHprazRSUkRYSGYxVm8KLS0tIE40VlV2NGozd0FKbExlZHAvaXRr
            RTR4cHlsWWJ0bVhnY0xxV3F4ZHJueUUKbNVk9LqlaHmMQ5QLfho9DVCT7+XDPLUW
            HuuGn36G5WYm6t6BOPey04FeYYv5CU4cp4Q1+0/PMWPAoQO65kBaCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T00:41:43Z"
    mac: ENC[AES256_GCM,data:89Xwj6TOJ+Gj6RTH6bOHTbVEYUqq0VgRVip+cX1NphDxLh6FIhm9umcXMK5UKPrGU57/qxTp9niOxKPf0amHaCx6t5Xom4bpZFBofiopI/vSuH2NoE3VbIxg0Fa9xBUurTkz8NHCmcmzsLyzOrI7bI94w6R0WQi6tPxRIGwDrU4=,iv:iszbiaokisjtmEmpFgm/a3E2t36OugQzdCbNUdAV+Xc=,tag:V6/KwFFttzspraNIuG2+pg==,type:str]
    version: 3.13.1
