---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: games
  namespace: gaming
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`games.becklab.cloud`)
      middlewares:
        - name: sso-admin-chain
          namespace: identity
      services:
        - name: rcon-web
          port: 4326
  tls:
    secretName: gaming-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rcon-web
  namespace: gaming
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rcon.becklab.cloud`)
      middlewares:
        - name: sso-admin-chain
          namespace: identity
      services:
        - name: rcon-web
          port: 4326
    - kind: Rule
      match: Host(`rcon.becklab.cloud`) && PathPrefix(`/ws/`)
      services:
        - name: oauth2-proxy
          namespace: identity
          port: 4180
  tls:
    secretName: gaming-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gaming
  namespace: gaming
spec:
  secretName: gaming-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - games.becklab.cloud
    - rcon.becklab.cloud