apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "simple-game-server-"
spec:
  ports:
  - name: default
    containerPort: 7654
  template:
    spec:
      serviceAccountName: my-special-service-account # a custom service account
      containers:
      - name: simple-game-server
        image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.43

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: gaming
  labels:
    app: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - name: http
      port: 25565
      targetPort: 25565
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pufferpanel
  namespace: gaming
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`games.becklab.cloud`)
      services:
        - name: minecraft
          port: 25565
  tls:
    secretName: gaming-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gaming
  namespace: gaming
spec:
  secretName: gaming-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - games.becklab.cloud
