apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-config
  namespace: gaming
  labels:
    app: crafty
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-world
  namespace: gaming
  labels:
    app: crafty
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-import
  namespace: gaming
  labels:
    app: crafty
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-logs
  namespace: gaming
  labels:
    app: crafty
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-backup
  namespace: gaming
  labels:
    app: crafty
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
