apiVersion: v1
kind: Secret
metadata:
    name: gaming-secrets
    namespace: gaming
stringData:
    rcon_password: ENC[AES256_GCM,data:9C9m2yZNqiYqUtNu5hw=,iv:Q2PKf7eIIyn0v+jCqegFbz2CV1eDyr3z7FkxuFpmTcI=,tag:W60qsKMkXpYp1cOD2J1GrQ==,type:str]
    postgres_password: ENC[AES256_GCM,data:iCVctIbJaKEI2nIlog==,iv:NecJcWUy4ewltNtH2hJWrc1dmAXHkhz0giSgEw36hzM=,tag:XbaeOV4PbPPGnjIOSWPhpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb3hJWkcrTmI0VFhXL045
            LzgzQldNeDNFbXRPNXZwM0FYdGNpVUJsTVNjCjBvdU0yUVlZRmtld1o3N1FVNFdu
            MHV6ZlNmL1FzZzdiVi90blRIWlhDTU0KLS0tIE8ydXZoZHpnK2FRdHEwMkRPYXJX
            ZktNNUQ5TmZHcndvTGtjZ0ZIbTI2cE0Kf3Jt2T9SM36/NqRu5jv44qnK5Q4Sun99
            lXBoapMdhw349QoaKUMIQcYsSHQhdT9Kutp9Uq/xeVHU61Q92tfZ4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T04:20:08Z"
    mac: ENC[AES256_GCM,data:RAqlVjNlT4oO88B5Ckyyp0dSAg5Dey1qk9QmPuofQhrEt+/NfHxVANc4V0FC8/1uJzm49u4rj7CiJ/S0XgpYuVy+LhrKZ0ci6t19OxjwHX0oB6SQzDkp3tKEysBshEqcRoly8neWl7i6bbB4dI2TKB1KYWpK6ACMZviLCrGUVOY=,iv:aWMONQ2X/2mX3BY76b5nC0HaCgymHLiLd7fqW2DNyfI=,tag:ZSIRPNHvrb/PLszoBKTw2A==,type:str]
    version: 3.13.1
