apiVersion: v1
kind: Secret
metadata:
    name: pufferpanel-secrets
    namespace: gaming
stringData:
    db_password: ENC[AES256_GCM,data:I4xZFyQOsEXIjY0JHIkuTa70TSxKKuFYWsCRgZ7g3D8=,iv:Z4InCe4BMYVo2YW7/5N8X1746UjKmLLZoI1Hb+P6BuM=,tag:VKJwVVRaF9YDH80IEBCtNg==,type:str]
    security_secret: ENC[AES256_GCM,data:+BU5V7mzn+Kum7yqKs0g/Dw9eFR3qB+EWoXFBlEcgLTcMlQEO3hPDEreVAA=,iv:LK6haBB+r4Z+T7Kyp5gzoNuAeW1OseHlohxvnimM4Qw=,tag:QVMvikBwsFen8qbxbVzdKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVnVzOFZydmNheTRsNXlk
            MDl5Uy9Zc0xMalJaTFpNUnAwL3B3MlJuNWprCm5XTVVSVStnK0w1NXJ0RXVkUjlU
            aWRLbHZhcGVKQXVleldUVERRekt6QzAKLS0tIEtnOS9WUysvc2lXM2pidEhSRDU4
            Rmdtb2Vad0d2ZWJpVWNTcS9YSnp0SlkK20pvl6Br7taXXXAqVVN34pXFClRCTFJj
            ZuHkUm35F56wnQMUl4ifN47NQ+TZhZ7z3ObumFaXeoYutmBwngDeYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T03:59:38Z"
    mac: ENC[AES256_GCM,data:dGIu8Qikgruog4MR2pAKH3p5gjPT9gor1ynpp+HdSUKQIgb8K8v98JEFjQ924j4TLc7zPeAjBr0f708zybGxkNlB/M62RJyaaIQg9ffL/ZQ2P2uGmbAh92ffegdVrf1NMeN2wKYck31zCo3H+2vZ519PaLO0pPBhPfFj+pyiZiw=,iv:QTdbKqCHiwGjkmnoWxP1Al1DnImS0uh430E4rnHlokM=,tag:c8dUv4q0/O6Fb1QtkkUi/A==,type:str]
    version: 3.13.1
