apiVersion: v1
kind: Service
metadata:
  name: admin-panel-frontend
  namespace: webapps
  labels:
    app: admin-panel-frontend
spec:
  selector:
    app: admin-panel-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
