apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: admin-panel-frontend
    files:
      - index.html=static/index.html
      - admin.js=static/js/admin.js
      - admin.css=static/css/admin.css
      - style.css=static/css/style.css
      - favicon.svg=static/favicon.svg
