apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ingressroute-admin-panel.yaml
  - resources/service-admin-panel.yaml
  - resources/deployment-admin-panel.yaml
  - resources/secret-admin-panel-secrets.yaml
  - resources/serviceaccount-admin-panel.yaml
  - resources/clusterrole-admin-panel-reader.yaml
  - resources/clusterrolobinding-admin-panel-reader-binding.yaml
  - resources/certificate-admin-panel.yaml
