apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media
  labels:
    app: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-100-11
      securityContext:
        fsGroup: 1000
      containers:
        - name: jellyseerr
          image: seerr/seerr:latest
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 512Mi
          env:
            - name: LOG_LEVEL
              value: debug
          ports:
            - containerPort: 5055
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: media
spec:
  selector:
    app: jellyseerr
  ports:
    - name: http
      port: 5055
      targetPort: 5055
      protocol: TCP
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: media
  labels:
    app: jellyseerr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`requests.becklab.cloud`)
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
      middlewares:
        - name: sso-media-chain
          namespace: identity
  tls:
    secretName: jellyseerr-tls
