# Auto-split from cluster files
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble
  namespace: monitoring
spec:
  secretName: hubble-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - hubble.becklab.cloud
