# Auto-split from cluster files
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    fullnameOverride: velero
    upgradeCRDs: false
    deployNodeAgent: true
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
    configuration:
      defaultVolumesToFsBackup: true
      uploaderType: restic
      volumeSnapshotLocation:
      - name: default
        provider: aws
        config:
          region: us-east-1
      backupStorageLocation:
      - name: default
        provider: aws
        bucket: velero-backups
        default: true
        config:
          region: us-east-1
          s3ForcePathStyle: 'true'
          s3Url: http://minio.velero.svc.cluster.local:9000
        credential:
          name: velero-credentials
          key: cloud
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.10.0
      volumeMounts:
      - name: plugins
        mountPath: /target
    schedules:
    - name: identity-6h
      schedule: 0 */6 * * *
      template:
        ttl: 720h0m0s
        includedNamespaces:
        - identity
        storageLocation: default
        snapshotVolumes: false
        defaultVolumesToFsBackup: true
    - name: security-daily
      schedule: 0 2 * * *
      template:
        ttl: 2160h0m0s
        includedNamespaces:
        - security
        storageLocation: default
        snapshotVolumes: false
        defaultVolumesToFsBackup: true
    - name: media-daily
      schedule: 0 1 * * *
      template:
        ttl: 336h0m0s
        includedNamespaces:
        - media
        - torrent
        excludedResources:
        - persistentvolumeclaims
        storageLocation: default
        snapshotVolumes: false
    - name: rancher-daily
      schedule: 0 4 * * *
      template:
        ttl: 720h0m0s
        includedNamespaces:
        - cattle-system
        storageLocation: default
        snapshotVolumes: false
        defaultVolumesToFsBackup: true
    - name: full-cluster-weekly
      schedule: 0 2 * * 0
      template:
        ttl: 2160h0m0s
        excludedNamespaces:
        - kube-system
        storageLocation: default
        snapshotVolumes: false
        defaultVolumesToFsBackup: true
