apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gridspace-app

images:
  - name: ghcr.io/yappingboy/becklab-gridspace
    newName: ghcr.io/yappingboy/becklab-gridspace
    newTag: latest
