apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.0
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
    urlPrefix: /
    ssl: false
    prometheusEndpoint: http://prometheus-prometheus-prometheus.monitoring.svc:9090
  network:
    provider: host
    connections:
      requireMsgr2: true
  storage:
    useAllNodes: true
    useAllDevices: false
    config:
      metadataDevice: /dev/nvme1n1
    devices:
      - name: sda
      - name: sdb
      - name: sdc
      - name: sdd
      - name: sde
      - name: sdf
      - name: sdg
      - name: sdh
      - name: sdi
      - name: sdj
      - name: sdk
      - name: sdl
      - name: sdm
      - name: sdn
      - name: sdo
      - name: sdp
  disruptionManagement:
    managePodBudgets: true
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 60s
      status:
        interval: 60s
  skipUpgradeChecks: true
  continueUpgradeAfterChecksEvenIfNotHealthy: false
