apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-server
  namespace: llama-cpp
  labels:
    app: llama-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-server
  template:
    metadata:
      labels:
        app: llama-server
    spec:
      containers:
      - name: llama-server
        image: unsloth/unsloth:latest
#        image: ghcr.io/ggml-org/llama.cpp:full-cuda
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: "all"
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "compute,utility"
#          - name: OMP_NUM_THREADS
#            value: "14"
#          - name: GOMP_CPU_AFFINITY
#            value: "0-14"
        imagePullPolicy: IfNotPresent
        args:
#          - "--server"
#          - "-m"
#          - "/models/Qwen3.8-Flash-Next-UD-IQ4_XS-00001-of-00003.gguf"
#          - "--host"
#          - "0.0.0.0"
#          - "--port"
#          - "8080"
#          - "--threads"
#          - "20"
#          - "--threads-batch"
#          - "20"
#          - "--flash-attn"
#          - "on"
#          - "--cache-type-k"
#          - "q4_0"
#          - "--cache-type-v"
#          - "q4_0"
#          - "-c"
#          - "262144"
#          - "--spec-type" 
#          - "draft-mtp" 
#          - "--spec-draft-n-max" 
#          - "2"
#          - "-md" 
#          - "/models/MTP/mtp-Qwen3.8-Flash-Next-Q8_0.gguf"
        ports:
          - containerPort: 8888
            name: jupyter
          - containerPort: 8000
            name: unsloth
          - containerPort: 22
            name: ssh
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: "14"
            memory: "80Gi"
          requests:
            nvidia.com/gpu: 1
            cpu: "14"
            memory: "48Gi"
        volumeMounts:
          - name: models
            mountPath: /workspace
#            readOnly: true
          - name: dshm
            mountPath: /dev/shm
      volumes:
        # Replaces -v ~/ollama:/models
        - name: models
          persistentVolumeClaim:
            claimName: llama-models
        # Replaces --ipc=host by providing full POSIX shared memory
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: llama-cpp
spec:
  type: NodePort
  selector:
    app: llama-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 31880  # Maps external port 30888 on your host to 8080 inside the pod
---
apiVersion: v1
kind: Service
metadata:
  name: unsloth-service
  namespace: llama-cpp
spec:
  type: NodePort
  selector:
    app: llama-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000  # Maps external port 30888 on your host to 8080 inside the pod
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  namespace: llama-cpp
spec:
  type: NodePort
  selector:
    app: llama-server
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 31022  # Maps external port 30888 on your host to 8080 inside the pod
