apiVersion: v1
kind: Service
metadata:
  name: embeddings-service
  namespace: llama-cpp
  labels:
    app: llama-server
spec:
  type: NodePort
  selector:
    app: llama-server
  ports:
    - name: embeddings
      protocol: TCP
      port: 36300
      targetPort: 36300
      nodePort: 31001
