## Copied to root volumeclaims.yaml
# PVCs for 3D printing services
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-models
  namespace: llama-cpp
spec:
  accessModes:
    - ReadWriteMany
  volumeName: llama-models-lvm
  storageClassName: "" 
  resources:
    requests:
      storage: 5Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-models-lvm
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /mnt/media/models
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-192-168-100-11
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unsloth-home
  namespace: llama-cpp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
