apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

resources:
  - namespace.yaml
  - wazuh.yaml
  - falco.yaml

helmReleases:
  - name: wazuh
    chart:
      repoURL: https://packages.wazuh.com/wazuh/4.9.0
      version: 4.9.0
      interval: 1m
  - name: falco
    chart:
      repoURL: https://charts.falco.org
      version: 4.24.0
      interval: 1m
