apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: crafty
  namespace: gaming
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`crafty.becklab.cloud`)
      middlewares:
        - name: sso-admin-chain
          namespace: identity
      services:
        - name: crafty
          port: 8443
          scheme: https
  tls:
    secretName: crafty-tls
