apiVersion: v1
kind: Service
metadata:
  name: crafty
  namespace: gaming
  labels:
    app: crafty
spec:
  selector:
    app: crafty
  ports:
  - name: https
    port: 8443
    targetPort: 8443
  - name: dynmap
    port: 8123
    targetPort: 8123
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: crafty-minecraft
  namespace: gaming
  labels:
    app: crafty
spec:
  selector:
    app: crafty
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565
    nodePort: 31337
  type: NodePort
