apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoolman-app
  namespace: 3dprinting
  labels:
    app: spoolman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoolman
  template:
    metadata:
      labels:
        app: spoolman
    spec:
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
        fsGroup: 1000
        runAsGroup: 0
        supplementalGroups:
        - 1000
      containers:
      - name: filament-tracker
        image: ghcr.io/donkie/spoolman:0.22.1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: TZ
          value: America/New_York
        - name: SPOOLMAN_HOST
          value: 0.0.0.0
        - name: SPOOLMAN_PORT
          value: '8000'
        volumeMounts:
        - name: data
          mountPath: /home/app/.local/share/spoolman
        securityContext:
          capabilities:
            drop:
            - ALL
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: spoolman-data