apiVersion: v1
kind: Secret
metadata:
    name: manyfold-secret-key
    namespace: 3dprinting
stringData:
    secret-key: ENC[AES256_GCM,data:AKfTRxydB+GP60lbZdYAfjTbZum+YjFLpY0buzAgEpmS0GdXO+Azwz7fyyCoPuAFkqsSWTTSsUZivDoyIioKTA==,iv:XAx2Tnr+wVYwOhS2CMYJlHDWyxiUzBPzUIgN5hRdVqA=,tag:xPAdwXnKzzmngcYotEIOGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeWc4Q2pqUE55c2V5S3hS
            ditpTTNtdVFJR0tQWGhzVHMzemdSRVpMTmhvCjMwVE0rclJyaEhzRHhkSWxKOTRr
            ZXh4THBlbnpOc1IrcDgwRkpJUVRvdEkKLS0tIDNOQ3FXV3lBaThyZy96SkFwSUlE
            UysvTXV5dHlsN2Y4bUFnaW96VTBSNTgKKliVPet69hTXM7mVVYZIuDaR8+3Kt94G
            JJw3UFwzai8ALvKEcF/6TxZJYm6AX7do0bo4/yVGyVW83QqwRAUfqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T19:44:32Z"
    mac: ENC[AES256_GCM,data:iTToFeszjuxIuIo0nfKPUWtdfykwajER96bWn656M+v5PAzaD81JQEaB6i8zVp3r/vVLCbEaIELt4g04dNGn79cjFtqwxf33Gak+6lF0WdH3nCqDWM/IzDhkXyL+CXsvf9aZ2h8UvfZ87UIx+ITM61B3dQ2l58Hw4YIMg8vZPmE=,iv:PenPbx2qBn1A7uDtATvj+ba3Z6M2rsrio8zLCoawKCU=,tag:FvvYCmkRWu+SeZPe0mBMgQ==,type:str]
    version: 3.13.2
