apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-redirect-html
  namespace: identity
data:
  admin-index.html: |
    <!DOCTYPE html>
      <html>
        <head><meta charset=\"utf-8\"><title>Signing in...</title></head>
        <body><p>Signing in, please wait...</p>
          <script>
            (function()
            {
              var rd = encodeURIComponent(window.location.href);
              window.location.replace('https://oauth2.becklab.cloud/oauth2/start?rd=' + rd);
            })();
          </script>
        </body>
    </html>
  media-index.html: |
    <!DOCTYPE html>
      <html>
        <head><meta charset=\"utf-8\"><title>Signing in...</title></head>
        <body><p>Signing in, please wait...</p>
          <script>
            (function()
            {
              var rd = encodeURIComponent(window.location.href);
              window.location.replace('https://oauth2-media.becklab.cloud/oauth2/start?rd=' + rd);
            })();
          </script>
        </body>
    </html>
  default.conf: |
    pid /tmp/nginx.pid
    server {
       listen 80;
       location / {
            root /usr/share/nginx/html/admin;
            index index.html;
       }    
       location /media {
            alias /usr/share/nginx/html/media/;
            index index.html;
            try_files $uri $uri/ /media/index.html;
       }
    }
