apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-redirect
  namespace: identity
  labels:
    app: sso-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-redirect
  template:
    metadata:
      labels:
        app: sso-redirect
    spec:
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 1000
#        fsGroup: 1000
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/admin/index.html
          subPath: admin-index.html
        - name: html
          mountPath: /usr/share/nginx/html/media/index.html
          subPath: media-index.html
        - name: html
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 32Mi
        securityContext:
          capabilities:
            drop:
            - ALL
      volumes:
      - name: html
        configMap:
          name: sso-redirect-html
