apiVersion: v1
kind: LimitRange
metadata:
  name: cert-manager-limits
  namespace: cert-manager
spec:
  limits:
    - type: Container
      default:
        cpu: 300m
        memory: 128Mi
      defaultRequest:
        cpu: 25m
        memory: 32Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cert-manager-quota
  namespace: cert-manager
spec:
  hard:
    pods: "6"
    requests.cpu: 500m
    requests.memory: 256Mi
    limits.cpu: "1"
    limits.memory: 512Mi
