apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hasher
  namespace: micro
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hash.tools.becklab.cloud`)
      kind: Rule
      services:
        - name: hasher
          port: 80
          sticky: false
