# GitHub Container Registry credentials for pulling images
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: identity
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJlV0Z3Y0dsdVoySnZlVHBuYUhCZlRsTTNNR1pwUWtSeE5uaGlTbUpDTW5FelJIRllSRFZ1Tm05V1MxbEpNbnBTZDFrNCJ9LCJpbmRleC5kb2NrZXIuaW8iOnsiYXV0aCI6ImVXRndjR2x1WjJKdmVUcGtZMnR5WDNCaGRGOXBkRXB2VjI5d1FsZ3pVMlZSTnpkbE9YZDJkRmhNV2pkUGEwaz0ifX19
