apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - namespace.yaml
  - pvcs.yaml
  - audit-sync
  - email
  - keycloak
  - lldap
  - logout-page
  - oauth2proxy
  - rbac
  - redis
  - role-enforcer
  - sso
  
