apiVersion: v1
kind: LimitRange
metadata:
  name: identity-limits
  namespace: identity
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: identity-quota
  namespace: identity
spec:
  hard:
    pods: "16"
    requests.cpu: "2"
    requests.memory: 6Gi
    limits.cpu: "8"
    limits.memory: 12Gi
