# Copied to volumeclaims.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: identity
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
