apiVersion: v1
kind: Secret
metadata:
    name: lldap-admin-password
    namespace: identity
stringData:
    admin-password: ENC[AES256_GCM,data:dY+HU+skuVK+,iv:0cwL8ce7Y/jAN9zPXZz84OGwMMDH6GyTGaz8bdJrir4=,tag:B1mEnGJOv6HWGv67TZsvMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV2NmcEg1NzZzdFhIM25z
            ZmNKdHpXKytsMWlzcDBUaTlDeS9xQ2ZOM0ZvClp6QXNjOGVDQUFEcXVBTG1ZeUpG
            YmJRTGNpTERqTUpxVFNhUDA0dUhMTU0KLS0tIGx0b2NJVVFFREN5dkZyOUx5U1lp
            YkhKdW1QTXkrS0RJd29nNnlUUmpXSE0KFLgATNPlcyFaDiulVEmdRvxKaJquVkgr
            kKKEJWgIJqeVQXWPJWFJIuRV1CjiYdTILPE0RSMnLJSccPLUr4FfMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:37:32Z"
    mac: ENC[AES256_GCM,data:PZsUToNpE+DqY8/aQwZKg3k+zDlpRM2mHOgHMKlXplMWiXZXdoqIjudWsegE6WdX83FTXdkv/++U7bG//ZrH0BPDU+cgA1g/4DfoVApcMNfnQvXAisnMe+Ygj/2m6f4oscWpodUHcPqxdrujEo+bdGI/njLNPEpnpiT9erQKu1w=,iv:g8w/1Xr9nhYmooAQU7Fx+YEqaRFhaLS5fO37u8YwyAc=,tag:Bs05RJv8KeqCAufLN0f9zA==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-database
    namespace: identity
stringData:
    username: ENC[AES256_GCM,data:/+zW9d8=,iv:Ng/zSQUqlTHeMUDB3toW7patXC39hq1DpPCQyK1UxLY=,tag:y3cj0SvB5aAbehK36GKiYA==,type:str]
    password: ENC[AES256_GCM,data:wiOdh20fOnHz,iv:CqHkVFyMg4JbDNncADN3w80H6k67mrtl5IrPH/GkNrw=,tag:fZZ+Dl7DGVCpIkcBropaHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV2NmcEg1NzZzdFhIM25z
            ZmNKdHpXKytsMWlzcDBUaTlDeS9xQ2ZOM0ZvClp6QXNjOGVDQUFEcXVBTG1ZeUpG
            YmJRTGNpTERqTUpxVFNhUDA0dUhMTU0KLS0tIGx0b2NJVVFFREN5dkZyOUx5U1lp
            YkhKdW1QTXkrS0RJd29nNnlUUmpXSE0KFLgATNPlcyFaDiulVEmdRvxKaJquVkgr
            kKKEJWgIJqeVQXWPJWFJIuRV1CjiYdTILPE0RSMnLJSccPLUr4FfMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:37:32Z"
    mac: ENC[AES256_GCM,data:PZsUToNpE+DqY8/aQwZKg3k+zDlpRM2mHOgHMKlXplMWiXZXdoqIjudWsegE6WdX83FTXdkv/++U7bG//ZrH0BPDU+cgA1g/4DfoVApcMNfnQvXAisnMe+Ygj/2m6f4oscWpodUHcPqxdrujEo+bdGI/njLNPEpnpiT9erQKu1w=,iv:g8w/1Xr9nhYmooAQU7Fx+YEqaRFhaLS5fO37u8YwyAc=,tag:Bs05RJv8KeqCAufLN0f9zA==,type:str]
    version: 3.13.0
