apiVersion: v1
kind: Secret
metadata:
    name: lldap-admin-password
    namespace: identity
stringData:
    admin-password: ENC[AES256_GCM,data:BNsfPkhoTvzbTw==,iv:SgeEQX7DtX8arQCpJdrVBAUpxLFBIUX8lUaDb6KZhXA=,tag:/WrOkSV4X3HlpcZID3PnSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV2NmcEg1NzZzdFhIM25z
            ZmNKdHpXKytsMWlzcDBUaTlDeS9xQ2ZOM0ZvClp6QXNjOGVDQUFEcXVBTG1ZeUpG
            YmJRTGNpTERqTUpxVFNhUDA0dUhMTU0KLS0tIGx0b2NJVVFFREN5dkZyOUx5U1lp
            YkhKdW1QTXkrS0RJd29nNnlUUmpXSE0KFLgATNPlcyFaDiulVEmdRvxKaJquVkgr
            kKKEJWgIJqeVQXWPJWFJIuRV1CjiYdTILPE0RSMnLJSccPLUr4FfMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:50:42Z"
    mac: ENC[AES256_GCM,data:KZwPwgCI+q38MWOe3GfBjzhkRvBLmvN0kjdvKDvBGZ0QSgpDaKWkqX+81A0sYdDI0rolcls2FxENJLIVYGO+t938Wi6RHLQMN/z5szbWGcgs7l+77TSk4OhoHlRl1tqOxhULJcWlJ/T2m0aY6yRKQzrQ8m893jdVF0fpIxAnezE=,iv:+SnT3dq7B7qQy8hdxjScVrVJ2bQKYp7G8tvZguOH4po=,tag:dyiMg9SlDkCfMWxItmGJlg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-database
    namespace: identity
stringData:
    username: ENC[AES256_GCM,data:/+zW9d8=,iv:Ng/zSQUqlTHeMUDB3toW7patXC39hq1DpPCQyK1UxLY=,tag:y3cj0SvB5aAbehK36GKiYA==,type:str]
    password: ENC[AES256_GCM,data:NNZaOksQefpj8pptq/Z3xT48VcyW7QZ8/j29wbW/I3uGrK4nsGiRBZs50cIe5KkrbkX2Mb1mmW7O8g7OF5Bvyw==,iv:SNpFTatF6yxmSxhGrSU1MDIVSwv93qvGwghSSGzAbkw=,tag:3iSnx17DsFoROaHNSyNClw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV2NmcEg1NzZzdFhIM25z
            ZmNKdHpXKytsMWlzcDBUaTlDeS9xQ2ZOM0ZvClp6QXNjOGVDQUFEcXVBTG1ZeUpG
            YmJRTGNpTERqTUpxVFNhUDA0dUhMTU0KLS0tIGx0b2NJVVFFREN5dkZyOUx5U1lp
            YkhKdW1QTXkrS0RJd29nNnlUUmpXSE0KFLgATNPlcyFaDiulVEmdRvxKaJquVkgr
            kKKEJWgIJqeVQXWPJWFJIuRV1CjiYdTILPE0RSMnLJSccPLUr4FfMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:50:42Z"
    mac: ENC[AES256_GCM,data:KZwPwgCI+q38MWOe3GfBjzhkRvBLmvN0kjdvKDvBGZ0QSgpDaKWkqX+81A0sYdDI0rolcls2FxENJLIVYGO+t938Wi6RHLQMN/z5szbWGcgs7l+77TSk4OhoHlRl1tqOxhULJcWlJ/T2m0aY6yRKQzrQ8m893jdVF0fpIxAnezE=,iv:+SnT3dq7B7qQy8hdxjScVrVJ2bQKYp7G8tvZguOH4po=,tag:dyiMg9SlDkCfMWxItmGJlg==,type:str]
    version: 3.13.0
