apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: identity
stringData:
    #ENC[AES256_GCM,data:KSivgODca2BepMjumZ5GRqxLsp8MUK92MSLAJIk/eRfnfoFLpa/2sxsH5vSm1yqGW6s8sxhrSQNEOVxS74YBLahKgMVUS6AS66aQTfkV,iv:AJ5xPvTDhH0Sy+dFWHVX02zmC2atdAXDPxO1LbMTlDo=,tag:DZHoVXAI4UeJSE8EjEYdyA==,type:comment]
    client-secret: ENC[AES256_GCM,data:w4/jJEK/SjV0tbU/+akl29AmVyYA0wZVJdF6AdxvNv8=,iv:HGiedlCSKkwZs7r4/Q6asxCuCIui6UAm+X4matbZDiU=,tag:TkEMpQeviWnoJYceKujN8g==,type:str]
    #ENC[AES256_GCM,data:A9AsMYRohmXBtSGkDpxL3Tni2zzAi/kuGuisMjDL9bQtoEu/CdxbfT28l4YiTOM8DKmsTGaB,iv:m6W9FnTJQtOgDH6Wr1r4Pp9tlYa65i5DpfyKS4VSVBE=,tag:1HEmja+KebVUYUqIXnsqcw==,type:comment]
    cookie-secret: ENC[AES256_GCM,data:UrY59C9siLNYA57mhKPGR4bBO3Q0EP1pdYHV9vZ+DCY=,iv:bWVWiAO9oFg4Z6AcWjKEtCYp5Hzlf1p5lVorAwzZZPY=,tag:QH0DbrawLJelooVvZrx8iQ==,type:str]
    client-id: ENC[AES256_GCM,data:fW509GHZBUNDhilV,iv:cdGAr3PBF2kpKW1QPVujljJ1998sBHKdxxpSR+am7oE=,tag:db6lOpL+U0K9UPmo2wIOxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab04wSlhVenJ3MlhaaVZK
            ZTBCZzltRVY1MW14dnRRditObE1HVWRkM2tNCjZmb3NXR3o3Y1FGRkZjMkxKREJX
            NS9lRzE1ZXNTakZZd3FoN0dWYmJyQkUKLS0tIHFpd2dTaDJnd3pqOFdaaEtuc28y
            d3Y1U3pMWmlhMDhqL2dYam9ncEFocVEK+EoH6cqWqmnXslgD4pWDT1y7bQpUPPp7
            dGl7ugVgBgP26/rJj7mmYmQCvGx3pQ5Au3uOs8m33etYihxzypyqtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15f2mn6pl769c22z8hw6mtrsna8l7fehml4j0m6jn573cs9vahcjsdrxh20
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T23:38:22Z"
    mac: ENC[AES256_GCM,data:Zh1wb9hYEn0l3gzAYc0hw9LnvW68zFbbg2xpeqajNYWtmJ6WZ3xMKYfWKvPnjBL4M+uXGJtQuewPpjbmnlV/y1mdbg11XVP4tBKkkHxiklf38xkTIRenuC8HRlYPAOevfrpJIH9Nt79jzQrzGHAvfIMFuiZVbQOCeZRUvY+/Rm0=,iv:6unzf6R7I8KBcyE8vlFlcMgK4giqeR9uxR/MsfsV7Wg=,tag:cZ6WR9MNIQTJt8wuMPJtyw==,type:str]
    version: 3.13.0
