apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: identity
stringData:
    #ENC[AES256_GCM,data:KSivgODca2BepMjumZ5GRqxLsp8MUK92MSLAJIk/eRfnfoFLpa/2sxsH5vSm1yqGW6s8sxhrSQNEOVxS74YBLahKgMVUS6AS66aQTfkV,iv:AJ5xPvTDhH0Sy+dFWHVX02zmC2atdAXDPxO1LbMTlDo=,tag:DZHoVXAI4UeJSE8EjEYdyA==,type:comment]
    client-secret: ENC[AES256_GCM,data:ArT4rUThapSK,iv:7GBd2le7M8cnmWNn610EZr1iIbe5Kx1JvXzpWsYt4sU=,tag:bkHjBUOZ9XKFTBHpn3wVdA==,type:str]
    #ENC[AES256_GCM,data:A9AsMYRohmXBtSGkDpxL3Tni2zzAi/kuGuisMjDL9bQtoEu/CdxbfT28l4YiTOM8DKmsTGaB,iv:m6W9FnTJQtOgDH6Wr1r4Pp9tlYa65i5DpfyKS4VSVBE=,tag:1HEmja+KebVUYUqIXnsqcw==,type:comment]
    cookie-secret: ENC[AES256_GCM,data:+OquHIVaMP0W,iv:sSBiM/5srk1V5yzx3FgGGYT2Ko1fqG3w9/solaJRH/Y=,tag:cwvReh7sLtRKEmNJm6w7TQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRGw0b28wRzhaOWVMREFZ
            SEI4WEJpYU9NZ1k1TEVqTzNDSGlHa3hoY3dVCkxqcjM1andQM2ExRFpPZ2FVclFV
            a0xWeFhtRnIxUTYzMFNveFR6TURXckkKLS0tIFY5NUEyZUlramlXcjJOTTdudkQ3
            bXlWZktpZUU3ZnBTSllKK3huU1ZSQnMKEsFRqrwPGZYB+QDBTz9Hd4XGWA1dmM9I
            mVhM6M+X7uQ2bEibjFQZKVn9MXlAxxrVcRRlbLYIrODHDzlWO3U62w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:37:32Z"
    mac: ENC[AES256_GCM,data:pSwl7zsvi0/SSySU9W3awG4RH0tSvkHfkAklOwZ965xodb/8AKfV4T0uO6Dp+ZrR+kj2fYgC0uuMDCFJoslx55j3Wc/aLNjjvw8aaUC7tr1+ORIAYyHz/FhX5kxHxKmqyx/o3LZPfyTrrOLzXLnieZKAahbc7KKsHKTLKC/PCNM=,iv:eMOnUrfDYLaa2+qERmg+HQHN7WAbusvvap8V5FhqCwU=,tag:C7ogssLYPMLHzOOxrUKLDg==,type:str]
    version: 3.13.0
