apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-password
    namespace: identity
stringData:
    admin-password: ENC[AES256_GCM,data:E8+ZRXeZBNjXFw==,iv:/7bpl3L+/ia5EGshO1khsfQGEQYLnjiRiFAFleTInEc=,tag:Vy3INRgrQpaijzkx7wBERA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTjJtbzJteWV6Q1MwczJM
            aEpBamtXSy9XWjdBYnhuaUFVcFhhS214MDNVCnhsVC9GOXNYZkdqN0ZJTFl3N210
            Q2pRS053QjFXRGtjL0tsdHNxbmJySDgKLS0tIDB6UTdkM29pdHVpN2Z6Y1NLWGs2
            VmVXWWgwZ0xKL1ZpMUd4N1FtamlrQzgKCPMbUI/Cvkho2yLTGCSkIed5On359MPo
            a6nrOdVJpu2t+3oujBWu3s16VZP1TmmtmdS3DAtAHbw8YQi6NXGdOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:51:42Z"
    mac: ENC[AES256_GCM,data:7hG212dBbjJhN+cqyDoG/PqjgWHi1qySFejGcLIrxbKccEeFvKNRcfJ8pxwo2BS3/y3CJiqZ9w65eeGNWCDhs8yzcftXtA270qebbdEp6UA3nDFAwphGAaIoGNUKo8lwiDAPRg3o4c6JqulPWI6bwPewM2jzNESEX/he51eeDQI=,iv:nGOOSyneY/lMNXV72/YexkpVjCm28k9QSLG0iWbZRI0=,tag:JPk8eEYltisL/BGZCyHI9w==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres-password
    namespace: identity
stringData:
    password: ENC[AES256_GCM,data:6F7Wfo0MwvNDgBE5V59dPO7cXtv3NbV6YVmSy3Q0OdA6c2m5fFliVb/nKt59bgAX2eO6Bk/CrP3qtUuCzKXVSA==,iv:r2/C8cUQo0SxO9Vko9jrKWzEzn41z7a4wFhuAQ6hmxM=,tag:bPAkRmuiIYiWuoEGkTPHSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTjJtbzJteWV6Q1MwczJM
            aEpBamtXSy9XWjdBYnhuaUFVcFhhS214MDNVCnhsVC9GOXNYZkdqN0ZJTFl3N210
            Q2pRS053QjFXRGtjL0tsdHNxbmJySDgKLS0tIDB6UTdkM29pdHVpN2Z6Y1NLWGs2
            VmVXWWgwZ0xKL1ZpMUd4N1FtamlrQzgKCPMbUI/Cvkho2yLTGCSkIed5On359MPo
            a6nrOdVJpu2t+3oujBWu3s16VZP1TmmtmdS3DAtAHbw8YQi6NXGdOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:51:42Z"
    mac: ENC[AES256_GCM,data:7hG212dBbjJhN+cqyDoG/PqjgWHi1qySFejGcLIrxbKccEeFvKNRcfJ8pxwo2BS3/y3CJiqZ9w65eeGNWCDhs8yzcftXtA270qebbdEp6UA3nDFAwphGAaIoGNUKo8lwiDAPRg3o4c6JqulPWI6bwPewM2jzNESEX/he51eeDQI=,iv:nGOOSyneY/lMNXV72/YexkpVjCm28k9QSLG0iWbZRI0=,tag:JPk8eEYltisL/BGZCyHI9w==,type:str]
    version: 3.13.0
