apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-password
    namespace: identity
stringData:
    admin-password: ENC[AES256_GCM,data:fvrBfcOp01ut,iv:ZzyKCrBTL/oYTno0gmUitKz+qYEpwntoLb5Si7d63WA=,tag:MOK77YBGXB516LNUYe2V6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucmJqVEIybVZJRkxVR0lE
            MS91WDNrZ1pGb2xxUERzSFVvZXJiS1haT0g0CjVNQjJ5ZERYYUo1WEZVM1laa0d1
            VnJUeXZTQk5ULzFpc2RQRTF1cEtvdHcKLS0tIC9STWtabDMwbDJTcHJsdjB2dnFI
            cmJ1QUdQRjN1cEpKUkhKaW9SK3htTFEK1yKUVlHq6Ojo4f9UZNghOk3Q5EoF4e0N
            ZZX7lZ7Un0W824m2TApEfQK+eVLyJAsFkY8X0nepcBvSq6s6CGNpog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:37:32Z"
    mac: ENC[AES256_GCM,data:2LUuA6evtnUn/UP2xmJg544AUe93LFOOKOZDv8XK6WOKc65GBck/HZ9AIpg6BTEj5J44hoVjH3VwwzafNiXzl7nB+6au/EvhRcNVF/vRZGXPu6PBq38G/jEnodm4gc3WdhforBJJVfwhUUJepyE/DNuA2domYhdStADHNdMy0vQ=,iv:QNkc723ArEfguY/SgaytzVzF9L9aSkW4dfvlXYCO5Gs=,tag:cCBOaQH8ZpcLsQkUnUp4mQ==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres-password
    namespace: identity
stringData:
    password: ENC[AES256_GCM,data:F/sQE80Jc2Vc,iv:KTVrOpleZv9hOZ8UMQYAROlZRxHfUKjJ1anq/g40lVI=,tag:xKLx7zO7W7F2IV8ppAV97w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucmJqVEIybVZJRkxVR0lE
            MS91WDNrZ1pGb2xxUERzSFVvZXJiS1haT0g0CjVNQjJ5ZERYYUo1WEZVM1laa0d1
            VnJUeXZTQk5ULzFpc2RQRTF1cEtvdHcKLS0tIC9STWtabDMwbDJTcHJsdjB2dnFI
            cmJ1QUdQRjN1cEpKUkhKaW9SK3htTFEK1yKUVlHq6Ojo4f9UZNghOk3Q5EoF4e0N
            ZZX7lZ7Un0W824m2TApEfQK+eVLyJAsFkY8X0nepcBvSq6s6CGNpog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:37:32Z"
    mac: ENC[AES256_GCM,data:2LUuA6evtnUn/UP2xmJg544AUe93LFOOKOZDv8XK6WOKc65GBck/HZ9AIpg6BTEj5J44hoVjH3VwwzafNiXzl7nB+6au/EvhRcNVF/vRZGXPu6PBq38G/jEnodm4gc3WdhforBJJVfwhUUJepyE/DNuA2domYhdStADHNdMy0vQ=,iv:QNkc723ArEfguY/SgaytzVzF9L9aSkW4dfvlXYCO5Gs=,tag:cCBOaQH8ZpcLsQkUnUp4mQ==,type:str]
    version: 3.13.0
