apiVersion: v1
kind: Secret
metadata:
    name: lldap-admin-password
    namespace: identity
stringData:
    admin-password: ENC[AES256_GCM,data:BNsfPkhoTvzbTw==,iv:SgeEQX7DtX8arQCpJdrVBAUpxLFBIUX8lUaDb6KZhXA=,tag:/WrOkSV4X3HlpcZID3PnSg==,type:str]
    key-seed: ENC[AES256_GCM,data:L/453IUNZb0x3Wwncx0Zduu+ItCNUV1ytGPD3dscKF57ynP5VTFOzJhBqAn3RKxRVPcno7licuwGVXkC338yhQ==,iv:dDERnQdEKxhtMu1wQWf+jHG6A0CWdPz/kjAkEYZ7KOg=,tag:/AAMl415erMRrfZ1LUaPpA==,type:str]
    jwt-secret: ENC[AES256_GCM,data:zDfDvvPpn7mw97tnUodgUxvvZZ3gKol7cBOFzlYCTpiog2ZGrbvSw19aCfgbwMcqXCJpgd4lxXmqi7AdGPLGyw==,iv:Z/OcMTqMVcjwy4ScigXK38K9jy1+qpM8jWlsjvKNlxU=,tag:rcCTF7ppksN9dbn73CodLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV2NmcEg1NzZzdFhIM25z
            ZmNKdHpXKytsMWlzcDBUaTlDeS9xQ2ZOM0ZvClp6QXNjOGVDQUFEcXVBTG1ZeUpG
            YmJRTGNpTERqTUpxVFNhUDA0dUhMTU0KLS0tIGx0b2NJVVFFREN5dkZyOUx5U1lp
            YkhKdW1QTXkrS0RJd29nNnlUUmpXSE0KFLgATNPlcyFaDiulVEmdRvxKaJquVkgr
            kKKEJWgIJqeVQXWPJWFJIuRV1CjiYdTILPE0RSMnLJSccPLUr4FfMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T19:30:27Z"
    mac: ENC[AES256_GCM,data:eMv8wbmc1yZfgbgXe+xzGp55nrsfqo90SMbUm3DVPFO4PdAlLRwAIZxwxsjT4+ts35fJDouHFS4cA17xg5cgT377TMdb7G4Yt7J8JK8QBKLYwR6j4oCJBn80+B2TB/lWqqnzi9Fso7FJbEL7Z43hlAVZMgn50sgCP5mIfMjItBY=,iv:KBHoZ0DPSBk6pnjkK0ikR7NdW6IcGtlQpbtU2gdDkMo=,tag:Q+AY9PlvcfZd0v74bJRvdg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-database
    namespace: identity
stringData:
    username: ENC[AES256_GCM,data:/+zW9d8=,iv:Ng/zSQUqlTHeMUDB3toW7patXC39hq1DpPCQyK1UxLY=,tag:y3cj0SvB5aAbehK36GKiYA==,type:str]
    password: ENC[AES256_GCM,data:NNZaOksQefpj8pptq/Z3xT48VcyW7QZ8/j29wbW/I3uGrK4nsGiRBZs50cIe5KkrbkX2Mb1mmW7O8g7OF5Bvyw==,iv:SNpFTatF6yxmSxhGrSU1MDIVSwv93qvGwghSSGzAbkw=,tag:3iSnx17DsFoROaHNSyNClw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV2NmcEg1NzZzdFhIM25z
            ZmNKdHpXKytsMWlzcDBUaTlDeS9xQ2ZOM0ZvClp6QXNjOGVDQUFEcXVBTG1ZeUpG
            YmJRTGNpTERqTUpxVFNhUDA0dUhMTU0KLS0tIGx0b2NJVVFFREN5dkZyOUx5U1lp
            YkhKdW1QTXkrS0RJd29nNnlUUmpXSE0KFLgATNPlcyFaDiulVEmdRvxKaJquVkgr
            kKKEJWgIJqeVQXWPJWFJIuRV1CjiYdTILPE0RSMnLJSccPLUr4FfMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dxutevuglwy4lc056qhc6errhgd2fwhxfc8lxlkkn2utyhdqepqr9gcc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T19:30:27Z"
    mac: ENC[AES256_GCM,data:eMv8wbmc1yZfgbgXe+xzGp55nrsfqo90SMbUm3DVPFO4PdAlLRwAIZxwxsjT4+ts35fJDouHFS4cA17xg5cgT377TMdb7G4Yt7J8JK8QBKLYwR6j4oCJBn80+B2TB/lWqqnzi9Fso7FJbEL7Z43hlAVZMgn50sgCP5mIfMjItBY=,iv:KBHoZ0DPSBk6pnjkK0ikR7NdW6IcGtlQpbtU2gdDkMo=,tag:Q+AY9PlvcfZd0v74bJRvdg==,type:str]
    version: 3.13.0
