apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-becklab
  namespace: identity
spec:
  secretName: mail-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - mail.becklab.cloud
