apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-main
  namespace: identity
data:
  main.cf: 'inet_interfaces = all

    inet_protocols = ipv4

    myhostname = mail.becklab.cloud

    mydomain = becklab.cloud

    myorigin = $mydomain

    mydestination = $myhostname, localhost.$mydomain, localhost

    mynetworks = 10.42.0.0/16 10.43.0.0/16 172.16.0.0/16 192.168.100.0/24 127.0.0.0/8

    relayhost = [smtp.mailgun.org]:587

    smtp_sasl_auth_enable = yes

    smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd

    smtp_sasl_security_options = noanonymous

    smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination

    smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination

    smtp_tls_security_level = may

    smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

    smtpd_tls_security_level = may

    smtpd_tls_cert_file = /etc/ssl/certs/mail.crt

    smtpd_tls_key_file = /etc/ssl/private/mail.key

    smtpd_tls_session_cache_database = btree:/var/lib/postfix/smtpd_scache

    message_size_limit = 10485760

    mailbox_size_limit = 0

    smtpd_client_message_rate_limit = 100

    smtpd_banner = $myhostname ESMTP

    '
---
