apiVersion: v1
kind: Secret
metadata:
    name: mailgun-smtp
    namespace: identity
stringData:
    sasl_passwd: ENC[AES256_GCM,data:08KL3GXU27wHsNR72quvV7FvK9y/M5COOOXhW5jSFHL8J79v2YRmKLhy078d/5AC2RKdkucF+GtpBCL0JWHjb0/ZnTRhd+eWeqgU5OlToBw3Y56xRsSkdZST+DXh,iv:Rd7zNSw8x6z8qAMB5Du7RvlMTbsXkMlD7CS/XuFe6y4=,tag:m4yky7gudZl4YP5L7RjHXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5U3JJVUNqV0dyWE9hemhx
            OTliZzZlTllDUjRJL0VueGxXaUF2UjJKa1NJClA4TzhIVlJDQ04yeHZQWFgrTzFQ
            dlVhcEd1YldHSDVtdGgvVDYxTkJDTFkKLS0tIGJDcURLQTl5K0Jua3E5b2JvM0hC
            VXhubER0dnpmVjNVTjZiWjk0ZEgyL0EKLw6Fu5QWMejUuHosi0BqSlSe4eYEetjT
            qbcIENSH4Ek7+T9d5xPLDPNPcTU/TLpLXqaToE8UVEJ+zrtbvF+LLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:04:25Z"
    mac: ENC[AES256_GCM,data:5WZ6eecsslXyj9o+yXUVwoNArhE8ySp+dch/3HJ4Qroj56cB8lljlwjZV4qe9IbCxvk9J6NjmvOdzYqmX84RbMECc3Z4JkUS0moOsczOQWIK4GNVYckzCRauWPNNMofJfICLK3CVlwg3gbw5EUpas3fN2xcBr+qosptElxmiod4=,iv:UCfi3BHf6dbJlQMuylThRoJV7JidyZV0pJqI+ni7Ljk=,tag:G25DpCgZrH9Zqfar76gxnA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mailu-secrets
    namespace: identity
stringData:
    bootstrap_password: ENC[AES256_GCM,data:eK9MgxCJB5u4PvTRukQWxDpPc0E15cBb8nw+4oEYBDY=,iv:8fo9HIo9Iaw0WxtNoNl544SVATAECPrxsBgM5ZFQmEs=,tag:0HhVOeaoIr7oO+erNpkzQQ==,type:str]
    sql_password: ENC[AES256_GCM,data:Q9DzM1u216ghVAoweGnAP821dfFqIsXF/sk1jSplCDM=,iv:WFNrYKar5oniah6NBQzjn/mX8L8hX8YuxyvonDD+6yc=,tag:hs5xVBlOwU5b9eyvZIjSkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN2lTSmVZQnlaT0lKREVL
            QlgyMkpNcUxIU0FyS1l6aW9ZMVh2TlR2cGtFCkxKbVZZNmhmTGNGNjF0b292MTZL
            WWJ5b29MSzVORmtabVdlbkFCdzJKeWsKLS0tIENGdjhzOFRyaGRyRDFpaGthRWNI
            OXBaMzJsQTRvRW9Ea1M4dzJRaytQSGsKUNQgxeuzlW8eXPkZo1gOuqUGD1yNFy3p
            hjLxZsYUg+ZOlridU5iOM97iHSRgK131n2cxu1+I35UBh8PvAfmGBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T04:13:58Z"
    mac: ENC[AES256_GCM,data:PietHORJKo4ppb6kgUtHhgL33ayooFYLrguSAD/Et9wjqG9bWnC1ieU9DZBdLCIpgYfB2EPMdvx0FQsm6NhRH1Xsaxeh9fLgWFhHEb6cGMOAc4/gRIYVPv4n3WPzMN7SzYgnd/HbfoM/26VomiJnAA9HxdFtFxUDG/b5/chvPyQ=,iv:mRa/CEntsc2FujCY/vLJ4bE/WapMMx2FgezWyXS6EC4=,tag:X4bwD9QrbeKGLxCxapOO2A==,type:str]
    version: 3.13.1
