apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: identity
  labels:
    app: postfix-relay
spec:
  selector:
    app: postfix-relay
  ports:
  - name: smtp
    port: 25
    targetPort: 25
    protocol: TCP
  - name: smtp-tls
    port: 587
    targetPort: 587
    protocol: TCP
  type: ClusterIP
