# Kaniko service account for build jobs in the micro namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-builder
  namespace: toolbox
  labels:
    app: kaniko-builder

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko-builder
  namespace: toolbox
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaniko-builder
  namespace: toolbox
subjects:
  - kind: ServiceAccount
    name: kaniko-builder
    namespace: toolbox
roleRef:
  kind: Role
  name: kaniko-builder
  apiGroup: rbac.authorization.k8s.io
