apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-service.yaml
  - ingressroutes.yaml
  - middlewares.yaml
  - services/deployments.yaml
  - services/svc-defs.yaml
  - services/rate-limits.yaml

images:
  # Hash / Base64 / URL Shortener / QR / YAML-JSON / Webhook / Cron / DNS
  - name: ghcr.io/yappingboy/hash
    newName: ghcr.io/yappingboy/hash
    newTag: latest
  - name: ghcr.io/yappingboy/converter
    newName: ghcr.io/yappingboy/converter
    newTag: latest
  - name: ghcr.io/yappingboy/url-shortener
    newName: ghcr.io/yappingboy/url-shortener
    newTag: latest
  - name: ghcr.io/yappingboy/qr-generator
    newName: ghcr.io/yappingboy/qr-generator
    newTag: latest
  - name: ghcr.io/yappingboy/yaml-json-tool
    newName: ghcr.io/yappingboy/yaml-json-tool
    newTag: latest
  - name: ghcr.io/yappingboy/webhook-relay
    newName: ghcr.io/yappingboy/webhook-relay
    newTag: latest
  - name: ghcr.io/yappingboy/cron-jobs
    newName: ghcr.io/yappingboy/cron-jobs
    newTag: latest
  - name: ghcr.io/yappingboy/dns-monitor
    newName: ghcr.io/yappingboy/dns-monitor
    newTag: latest
  # Auth service
  - name: ghcr.io/yappingboy/auth-micro
    newName: ghcr.io/yappingboy/auth-micro
    newTag: latest
  # Image Editor
  - name: ghcr.io/yappingboy/image-editor-api
    newName: ghcr.io/yappingboy/image-editor-api
    newTag: latest
  - name: ghcr.io/yappingboy/image-editor-frontend
    newName: ghcr.io/yappingboy/image-editor-frontend
    newTag: latest
  # BeckFlow
  - name: ghcr.io/yappingboy/beckflow
    newName: ghcr.io/yappingboy/beckflow
    newTag: latest
  - name: ghcr.io/yappingboy/beckflow-frontend
    newName: ghcr.io/yappingboy/beckflow-frontend
    newTag: latest
