apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-service.yaml
  - services/deployments.yaml
  - services/svc-defs.yaml
  - services/metrics.yaml
  - services/rate-limits.yaml
  - services/grafana-dashboard-cm.yaml
  - ingressroutes.yaml
  - middlewares.yaml
