# Auto-split from cluster files
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiparr
  namespace: media
  labels:
    app: swiparr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiparr
  template:
    metadata:
      labels:
        app: swiparr
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-100-11
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 1000
#        fsGroup: 1000
#        runAsGroup: 1000
#        supplementalGroups:
#        - 1000
      containers:
      - name: swiparr
        image: ghcr.io/m3sserstudi0s/swiparr:latest
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        ports:
        - containerPort: 4321
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: swiparr-env
        volumeMounts:
        - name: data
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        securityContext:
          capabilities:
            drop:
            - ALL
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: swiparr-data
