# Auto-split from cluster files
apiVersion: v1
kind: Secret
metadata:
  name: swiparr-env
  namespace: media
stringData:
  PROVIDER: jellyfin
  JELLYFIN_URL: http://jellyfin.media.svc.cluster.local:8096
  JELLYFIN_PUBLIC_URL: https://jellyfin.becklab.cloud
  PROVIDER_LOCK: 'true'
  USE_SECURE_COOKIES: 'true'
  PORT: '4321'
  HOSTNAME: 0.0.0.0
  DATABASE_URL: file:/app/data/swiparr.db
  USE_STATIC_FILTERS: 'false'
  ALLOW_PRIVATE_PROVIDER_URLS: 'true'
type: Opaque
