apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: cadam
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJlV0Z3Y0dsdVoySnZlVHBuYUhCZlpERnNNVmgxTTAxeU1uTm5SVUY0YVhWSmRrOTFkR3hSWVhrNVpGZG1ORmhWVEd0WCJ9fX0=
