apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghcr-credentials-cadam.yaml
  - ghcr-credentials-default.yaml
  - ghcr-credentials-gridspace.yaml
  - ghcr-credentials-media.yaml
  - ghcr-credentials-security.yaml
  - ghcr-credentials-webapps.yaml
