apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-service
- base64
- beckflow
- cron-jobs
- dns-monitor
- hash
- image-editor
- pricing-page
- prometheus
- qr-generator
- status-page
- url-shortener
- webhook-relay
- yaml-json-tool

