apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-service/deployment.yaml
- auth-service/ingress.yaml
- base64/deployment.yaml
- base64/ingress.yaml
- beckflow/deployment.yaml
- beckflow/ingress.yaml
- cron-jobs/deployment.yaml
- cron-jobs/ingress.yaml
- dns-monitor/deployment.yaml
- dns-monitor/ingress.yaml
- hash/deployment.yaml
- hash/ingress.yaml
- image-editor/api-deployment.yaml
- image-editor/frontend-deployment.yaml
- image-editor/ingress.yaml
- pricing-page/deployment.yaml
- prometheus/grafana-dashboard-configmap.yaml
- prometheus/servicemonitor.yaml
- qr-generator/deployment.yaml
- qr-generator/ingress.yaml
- status-page/deployment.yaml
- url-shortener/deployment.yaml
- url-shortener/ingress.yaml
- webhook-relay/deployment.yaml
- webhook-relay/ingress.yaml
- yaml-json-tool/deployment.yaml
- yaml-json-tool/ingress.yaml
