apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bw-tls
  namespace: bitwarden
spec:
  secretName: bw-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bw.becklab.cloud
