apiVersion: traefik.containo.dev/v1alpha1
kind: IngressRoute
metadata:
  name: bitwarden-secrets-manager
  namespace: bitwarden
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bw.becklab.cloud`)
      kind: Rule
      services:
        - name: bitwarden-secrets-manager
          port: 80
          scheme: https
      middlewares:
        - name: ssl-redirect
          namespace: traefik
        - name: oauth2-proxy
          namespace: identity
  tls:
    secretName: bw-tls
