# Auto-split from cluster files
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micro-services
  namespace: micro
  labels:
    app: micro-monitoring
spec:
  selector:
    matchLabels:
      monitoring: 'true'
  namespaceSelector:
    matchNames:
    - micro
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
