apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:YE7jrkHgMa3MrzUpWdYSzD7AURLJs4iAYMYMVkHvhe5LPAiMlCufW/GBudJxE1HFIROXLH+SMN2TR3Y979vQtVkZGfCWxxDwLCNThceatOVTMZXj,iv:xAw5go/K0hKAcDb+LPPldqopLqjeRtfDV2Xdl6XxPsY=,tag:d8VW69wYXzRtmd5dCwBmuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UUowRXJSOWpiVHlEMDRJ
            eWdqN0RXYzVON25RZmxXamE4RlI5TWY5MFVJCitHRGJXWUlobTFOYTNwNEtuNjJq
            eVlzUUV2RVBXMVk1ZGt5c0wweWEvUmMKLS0tIFBCdGZwWEM5KzN1bGFDaUI0K082
            VkZaYmRNamtQZkg0NWhEWVJrT0xEN28K9LbHWHY3bVTyYU/ip3fE3Y2PeyrtASYa
            dwyooX8YNT4KStSl7+hfm/C2oNRYxhWjYHLAo/V74esD7bgw3rzZHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T17:52:28Z"
    mac: ENC[AES256_GCM,data:j6fxRbbLInCbiCv9blfAlVqNl2/JfDAY8/9di0AceKdneJfT26bjZa/xr9v6lUBt1uFkL6A+/zrPyvLSU5gnRr8+lsN2vvHAXDYDNnVd0qlo7NYQGknW8oYzI5gC1LdJPlYcA/HuDAiG1unQ3Ql/847ad2zRKzJbwhpo+oUC0WE=,iv:pYHldnf8Il8Q6Et3wAWERZcGz4mcRBYOeZLOEzywegs=,tag:8KvNNN3Bg1EtPZHQSJKYqA==,type:str]
    version: 3.13.2
