apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - namespace.yaml
  - minio/pv.yaml
  - minio/pvc.yaml
  - minio/credentials.yaml
  - minio/deployment.yaml
  - minio/service.yaml
  - minio/bucket-init.yaml
  - credentials-secret.yaml
  - velero.yaml
  - ingressroute.yaml
