apiVersion: v1
kind: LimitRange
metadata:
  name: velero-limits
  namespace: velero
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: velero-quota
  namespace: velero
spec:
  hard:
    pods: "8"
    requests.cpu: 500m
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 4Gi
