apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tdarr

resources:
  - namespace.yaml
  - secret-tdarr-secrets.yaml
  - tdarr-deployment.yaml
  - tdarr-service.yaml
  - tdarr-ingressroute.yaml
  - tdarr-certificate.yaml