apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toolbox

resources:
  - namespace.yaml
  - ../user-invite/secret-ghcr-toolbox.yaml
  - ../user-invite/kaniko-build.yaml
  - ../gridspace/kaniko-build.yaml
  - ../gridspace/tina2s-configmap.yaml
  - ../gridspace/gridspace-dockerfile-cm.yaml
  - ../landing-page/kaniko-build.yaml
  - ../../infrastructure/micro/micro-app/build-jobs.yaml
  - ../../infrastructure/micro/micro-app/frontend-builds.yaml
