apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcaslicer
  namespace: 3dprinting
  labels:
    app: orcaslicer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orcaslicer
  template:
    metadata:
      labels:
        app: orcaslicer
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-100-11
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        runAsGroup: 1000
        supplementalGroups:
        - 1000
      containers:
      - name: orca-slicer
        image: ghcr.io/linuxserver/orcaslicer:1.9.0
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 2Gi
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: America/New_York
        ports:
        - containerPort: 3001
          name: https
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        securityContext:
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: orcaslicer-config