apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orcaslicer
  namespace: 3dprinting
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/middlewares: identity-sso-admin-chain@kubernetescrd
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  tls:
  - hosts:
    - slicer.becklab.cloud
    secretName: orcaslicer-tls
  rules:
  - host: slicer.becklab.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orcaslicer
            port:
              number: 3001
