apiVersion: v1
kind: Secret
metadata:
    name: directus-admin-password
    namespace: webapps
stringData:
    admin-password: ENC[AES256_GCM,data:Hgc5b3YOvAYC6qb3gz38kGhm/zUo5WwqMqucexlxAUsvCgTKXT2cas/cy9g=,iv:NPw0MGXACi5mED+wWXo5Q0Qwu21X1bqx1NthqINNAQs=,tag:UT7AbAanAzlj9iwrYhn8ZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dFJxK1FJdjFqWlNjUW01
            YWhkdHFFV3puM0Q4Vi93RXdTWkhhSDVkU0dVCjJ2NGREZW5qaWlzNFlHN3hVZndm
            QWM3MzRYYkpZZ0RLRWxZcTJXbktjZlkKLS0tIHc0OVpYeDRWUG5xamIwOUtKemdv
            cTJSM2tlbkZIdGppMFZQSndwVC94eGMKhceRpZ2bUjbQnSmpsd0WuzBmlOzz5wwl
            q1jEpOnLsiNvw4badqG3PQiX7roVcHp4FXl+bVWcS6TNQZaL4Y9RaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhl457qt9vxad0zvwuyweqz4vdhfm372y9cypkvrsqnx028cyqvqrq4u8w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T17:48:52Z"
    mac: ENC[AES256_GCM,data:ix5QUBsvcxlipYP2HJtu/NbDRg86LXMR3UMudkyRWEwcmzqq7zd9k3Xxz9qg9ar735nguFAxbRwWuAVEEv1X6it22RXXmVf9oS9ifoElrbKHqYvjkCXppdOfpOEDBPsqIMYdbqAjMkeFmce6WPD6mSIS++lZeHX0U0lGRnXQwQk=,iv:sD6kc+LDUCK7DqbUd2xJ8bQEznZ9f6sKLdR9uiqiQFs=,tag:V1SUy6dadsEW6HpStWlKsA==,type:str]
    version: 3.13.2
